/* Generated by Yosys 0.9+3565 (git sha1 474cd02e, gcc 9.3.0-10ubuntu2 -fPIC -Os) */

(* dynports =  1  *)
(* src = "control_logic_synth.v:1.1-80.10" *)
module control_logic_synth(full_threshold, empty_threshold, fifo_rd, fifo_wr, clk, reset_L, error_synth, almost_empty_synth, almost_full_synth, fifo_full_synth, fifo_empty_synth);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire _008_;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire _009_;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire _010_;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  wire _011_;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  wire _012_;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  wire _013_;
  (* src = "control_logic_synth.v:14.16-14.21" *)
  wire _014_;
  (* src = "control_logic_synth.v:18.16-18.26" *)
  wire _015_;
  (* src = "control_logic_synth.v:17.16-17.25" *)
  wire _016_;
  (* src = "control_logic_synth.v:10.11-10.18" *)
  wire _017_;
  (* src = "control_logic_synth.v:11.11-11.18" *)
  wire _018_;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  wire _019_;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  wire _020_;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  (* src = "control_logic_synth.v:13.11-13.18" *)
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire [1:0] _134_;
  wire _135_;
  wire _136_;
  wire [1:0] _137_;
  wire [1:0] _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire [15:0] _143_;
  wire [7:0] _144_;
  wire [1:0] _145_;
  wire [3:0] _146_;
  wire [2:0] _147_;
  (* src = "control_logic_synth.v:34.13-34.38" *)
  wire _148_;
  (* src = "control_logic_synth.v:42.13-42.39" *)
  wire _149_;
  (* src = "control_logic_synth.v:51.14-51.33" *)
  wire _150_;
  (* src = "control_logic_synth.v:51.14-51.46" *)
  wire _151_;
  (* src = "control_logic_synth.v:51.52-51.71" *)
  wire _152_;
  (* src = "control_logic_synth.v:51.52-51.85" *)
  wire _153_;
  (* src = "control_logic_synth.v:64.18-64.51" *)
  wire _154_;
  (* src = "control_logic_synth.v:51.13-51.86" *)
  wire _155_;
  (* src = "control_logic_synth.v:51.25-51.33" *)
  wire _156_;
  (* src = "control_logic_synth.v:51.63-51.71" *)
  wire _157_;
  (* src = "control_logic_synth.v:54.41-54.52" *)
  wire _158_;
  (* src = "control_logic_synth.v:64.41-64.51" *)
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire [2:0] _168_;
  wire [2:0] _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:65.24-65.35|write_logic_synth.v:24.23-24.33|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _174_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:65.24-65.35|write_logic_synth.v:24.23-24.33|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _175_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:65.24-65.35|write_logic_synth.v:24.23-24.33|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [31:0] _176_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.38|/usr/local/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [2:0] _177_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.38|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [2:0] _178_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.38|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _179_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.38|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [2:0] _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:70.22-70.34|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _185_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:42.13-42.39|/usr/local/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [2:0] _186_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:42.13-42.39|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [2:0] _187_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:42.13-42.39|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _188_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:42.13-42.39|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [2:0] _189_;
  wire _190_;
  wire _191_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:60.22-60.43|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _192_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:60.22-60.43|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2" *)
  wire [31:0] _193_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:55.24-55.35|memory_synth.v:30.17-30.25|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _194_;
  (* src = "control_logic_synth.v:34.13-34.38|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _195_;
  (* src = "control_logic_synth.v:34.13-34.38|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _196_;
  (* src = "control_logic_synth.v:42.13-42.39|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _197_;
  (* src = "control_logic_synth.v:42.13-42.39|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _198_;
  (* src = "control_logic_synth.v:15.16-15.28" *)
  output almost_empty_synth;
  (* src = "control_logic_synth.v:16.16-16.27" *)
  output almost_full_synth;
  (* src = "control_logic_synth.v:12.11-12.14" *)
  input clk;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire [2:0] counter;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  input [2:0] empty_threshold;
  (* src = "control_logic_synth.v:14.16-14.21" *)
  output error_synth;
  (* src = "control_logic_synth.v:18.16-18.26" *)
  output fifo_empty_synth;
  (* src = "control_logic_synth.v:17.16-17.25" *)
  output fifo_full_synth;
  (* src = "control_logic_synth.v:10.11-10.18" *)
  input fifo_rd;
  (* src = "control_logic_synth.v:11.11-11.18" *)
  input fifo_wr;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  input [2:0] full_threshold;
  (* src = "control_logic_synth.v:13.11-13.18" *)
  input reset_L;
  NOT _199_ (
    .A(_104_),
    .Y(_034_)
  );
  NOT _200_ (
    .A(_016_),
    .Y(_035_)
  );
  NOT _201_ (
    .A(_010_),
    .Y(_036_)
  );
  NOT _202_ (
    .A(_009_),
    .Y(_037_)
  );
  NOT _203_ (
    .A(_008_),
    .Y(_038_)
  );
  NOT _204_ (
    .A(_015_),
    .Y(_039_)
  );
  NOT _205_ (
    .A(_017_),
    .Y(_040_)
  );
  NOT _206_ (
    .A(_018_),
    .Y(_041_)
  );
  NOT _207_ (
    .A(_021_),
    .Y(_042_)
  );
  NOT _208_ (
    .A(_013_),
    .Y(_043_)
  );
  NOR _209_ (
    .A(_017_),
    .B(_041_),
    .Y(_044_)
  );
  NAND _210_ (
    .A(_040_),
    .B(_018_),
    .Y(_045_)
  );
  NOR _211_ (
    .A(_016_),
    .B(_045_),
    .Y(_046_)
  );
  NAND _212_ (
    .A(_035_),
    .B(_044_),
    .Y(_047_)
  );
  NAND _213_ (
    .A(_009_),
    .B(_008_),
    .Y(_048_)
  );
  NOT _214_ (
    .A(_048_),
    .Y(_049_)
  );
  NOR _215_ (
    .A(_047_),
    .B(_048_),
    .Y(_050_)
  );
  NAND _216_ (
    .A(_046_),
    .B(_049_),
    .Y(_051_)
  );
  NOR _217_ (
    .A(_010_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _218_ (
    .A(_036_),
    .B(_050_),
    .Y(_053_)
  );
  NAND _219_ (
    .A(_010_),
    .B(_009_),
    .Y(_054_)
  );
  NOR _220_ (
    .A(_040_),
    .B(_018_),
    .Y(_055_)
  );
  NAND _221_ (
    .A(_017_),
    .B(_041_),
    .Y(_056_)
  );
  NOR _222_ (
    .A(_015_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _223_ (
    .A(_039_),
    .B(_055_),
    .Y(_058_)
  );
  NOR _224_ (
    .A(_010_),
    .B(_009_),
    .Y(_059_)
  );
  NOR _225_ (
    .A(_009_),
    .B(_038_),
    .Y(_060_)
  );
  NAND _226_ (
    .A(_008_),
    .B(_059_),
    .Y(_061_)
  );
  NOT _227_ (
    .A(_061_),
    .Y(_062_)
  );
  NOR _228_ (
    .A(_058_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _229_ (
    .A(_057_),
    .B(_061_),
    .Y(_064_)
  );
  NAND _230_ (
    .A(_054_),
    .B(_063_),
    .Y(_065_)
  );
  NAND _231_ (
    .A(_016_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _232_ (
    .A(_053_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _233_ (
    .A(_104_),
    .B(_067_),
    .Y(_068_)
  );
  NOT _234_ (
    .A(_068_),
    .Y(_006_)
  );
  NOR _235_ (
    .A(_036_),
    .B(_057_),
    .Y(_069_)
  );
  NAND _236_ (
    .A(_051_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _237_ (
    .A(_059_),
    .B(_060_),
    .Y(_071_)
  );
  NAND _238_ (
    .A(_054_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _239_ (
    .A(_063_),
    .B(_072_),
    .Y(_073_)
  );
  NAND _240_ (
    .A(_070_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _241_ (
    .A(_052_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _242_ (
    .A(_034_),
    .B(_075_),
    .Y(_005_)
  );
  NOR _243_ (
    .A(_046_),
    .B(_057_),
    .Y(_076_)
  );
  NAND _244_ (
    .A(_047_),
    .B(_058_),
    .Y(_077_)
  );
  NAND _245_ (
    .A(_009_),
    .B(_076_),
    .Y(_078_)
  );
  NOR _246_ (
    .A(_037_),
    .B(_008_),
    .Y(_079_)
  );
  NOR _247_ (
    .A(_060_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _248_ (
    .A(_047_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _249_ (
    .A(_057_),
    .B(_080_),
    .Y(_082_)
  );
  NAND _250_ (
    .A(_078_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _251_ (
    .A(_081_),
    .B(_083_),
    .Y(_084_)
  );
  NOR _252_ (
    .A(_034_),
    .B(_084_),
    .Y(_004_)
  );
  NOR _253_ (
    .A(_008_),
    .B(_076_),
    .Y(_085_)
  );
  NOR _254_ (
    .A(_038_),
    .B(_077_),
    .Y(_086_)
  );
  NOR _255_ (
    .A(_085_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _256_ (
    .A(_034_),
    .B(_087_),
    .Y(_003_)
  );
  NOR _257_ (
    .A(_058_),
    .B(_061_),
    .Y(_088_)
  );
  NAND _258_ (
    .A(_064_),
    .B(_077_),
    .Y(_089_)
  );
  NOR _259_ (
    .A(_052_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _260_ (
    .A(_039_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _261_ (
    .A(_088_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _262_ (
    .A(_034_),
    .B(_092_),
    .Y(_002_)
  );
  NAND _263_ (
    .A(_037_),
    .B(_020_),
    .Y(_093_)
  );
  NAND _264_ (
    .A(_038_),
    .B(_019_),
    .Y(_094_)
  );
  NAND _265_ (
    .A(_093_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _266_ (
    .A(_036_),
    .B(_021_),
    .Y(_096_)
  );
  NOR _267_ (
    .A(_037_),
    .B(_020_),
    .Y(_097_)
  );
  NOR _268_ (
    .A(_096_),
    .B(_097_),
    .Y(_098_)
  );
  NAND _269_ (
    .A(_095_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _270_ (
    .A(_010_),
    .B(_042_),
    .Y(_100_)
  );
  NAND _271_ (
    .A(_104_),
    .B(_099_),
    .Y(_101_)
  );
  NOR _272_ (
    .A(_100_),
    .B(_101_),
    .Y(_001_)
  );
  NOR _273_ (
    .A(_037_),
    .B(_012_),
    .Y(_102_)
  );
  NOR _274_ (
    .A(_038_),
    .B(_011_),
    .Y(_103_)
  );
  NOR _275_ (
    .A(_102_),
    .B(_103_),
    .Y(_022_)
  );
  NAND _276_ (
    .A(_036_),
    .B(_013_),
    .Y(_023_)
  );
  NAND _277_ (
    .A(_037_),
    .B(_012_),
    .Y(_024_)
  );
  NAND _278_ (
    .A(_023_),
    .B(_024_),
    .Y(_025_)
  );
  NOR _279_ (
    .A(_022_),
    .B(_025_),
    .Y(_026_)
  );
  NAND _280_ (
    .A(_010_),
    .B(_043_),
    .Y(_027_)
  );
  NAND _281_ (
    .A(_104_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _282_ (
    .A(_026_),
    .B(_028_),
    .Y(_000_)
  );
  NAND _283_ (
    .A(_014_),
    .B(_076_),
    .Y(_029_)
  );
  NOR _284_ (
    .A(_039_),
    .B(_056_),
    .Y(_030_)
  );
  NAND _285_ (
    .A(_016_),
    .B(_044_),
    .Y(_031_)
  );
  NAND _286_ (
    .A(_029_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _287_ (
    .A(_030_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _288_ (
    .A(_034_),
    .B(_033_),
    .Y(_007_)
  );
  (* src = "control_logic_synth.v:22.1-78.4" *)
  DFF _289_ (
    .C(clk),
    .D(_120_),
    .Q(almost_empty_synth)
  );
  (* src = "control_logic_synth.v:22.1-78.4" *)
  DFF _290_ (
    .C(clk),
    .D(_121_),
    .Q(almost_full_synth)
  );
  (* src = "control_logic_synth.v:22.1-78.4" *)
  DFF _291_ (
    .C(clk),
    .D(_123_),
    .Q(fifo_empty_synth)
  );
  (* src = "control_logic_synth.v:22.1-78.4" *)
  DFF _292_ (
    .C(clk),
    .D(_125_),
    .Q(counter[0])
  );
  (* src = "control_logic_synth.v:22.1-78.4" *)
  DFF _293_ (
    .C(clk),
    .D(_127_),
    .Q(counter[1])
  );
  (* src = "control_logic_synth.v:22.1-78.4" *)
  DFF _294_ (
    .C(clk),
    .D(_129_),
    .Q(counter[2])
  );
  (* src = "control_logic_synth.v:22.1-78.4" *)
  DFF _295_ (
    .C(clk),
    .D(_131_),
    .Q(fifo_full_synth)
  );
  (* src = "control_logic_synth.v:22.1-78.4" *)
  DFF _296_ (
    .C(clk),
    .D(_133_),
    .Q(error_synth)
  );
  assign _137_[1] = 1'h1;
  assign _138_[0] = _113_;
  assign _143_[15:1] = { 14'h3fff, counter[2] };
  assign _144_[7:1] = 7'h7f;
  assign _145_[0] = _116_;
  assign { _146_[3], _146_[1] } = { 1'h1, _118_ };
  assign _147_[1:0] = { _145_[1], _116_ };
  assign { _174_[31:3], _174_[0] } = { 29'h00000000, counter[0] };
  assign _175_[31:1] = { 29'h00000000, counter[2:1] };
  assign { _176_[31:3], _176_[0] } = { 28'h0000000, _174_[2], _175_[0] };
  assign { _185_[31:3], _185_[0] } = { 29'h1fffffff, _175_[0] };
  assign { _192_[30:2], _192_[0] } = { _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], _192_[31], counter[0] };
  assign { _193_[30:3], _193_[0] } = { _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _193_[31], _175_[0] };
  assign { _194_[30:3], _194_[1:0] } = { _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _194_[31], _193_[1], _175_[0] };
  assign _014_ = error_synth;
  assign _104_ = reset_L;
  assign _131_ = _006_;
  assign _016_ = fifo_full_synth;
  assign _129_ = _005_;
  assign _010_ = counter[2];
  assign _127_ = _004_;
  assign _009_ = counter[1];
  assign _125_ = _003_;
  assign _008_ = counter[0];
  assign _123_ = _002_;
  assign _015_ = fifo_empty_synth;
  assign _121_ = _001_;
  assign _120_ = _000_;
  assign _017_ = fifo_rd;
  assign _018_ = fifo_wr;
  assign _019_ = full_threshold[0];
  assign _020_ = full_threshold[1];
  assign _021_ = full_threshold[2];
  assign _011_ = empty_threshold[0];
  assign _012_ = empty_threshold[1];
  assign _013_ = empty_threshold[2];
  assign _133_ = _007_;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "fifo.v:1.1-85.10" *)
module fifo_synth(fifo_data_out_synth, error_synth, almost_empty_synth, almost_full_synth, fifo_full_synth, fifo_empty_synth, fifo_wr, fifo_rd, fifo_data_in, full_threshold, empty_threshold, clk, reset_L);
  (* src = "fifo.v:10.12-10.24" *)
  output almost_empty_synth;
  (* src = "fifo.v:11.12-11.23" *)
  output almost_full_synth;
  (* src = "fifo.v:19.11-19.14" *)
  input clk;
  (* src = "fifo.v:78.24-78.34" *)
  wire [5:0] data_in_MM;
  (* src = "fifo.v:24.22-24.33" *)
  wire [5:0] data_out_MM;
  (* src = "fifo.v:18.23-18.38" *)
  input [2:0] empty_threshold;
  (* src = "fifo.v:9.12-9.17" *)
  output error_synth;
  (* src = "fifo.v:16.27-16.39" *)
  input [5:0] fifo_data_in;
  (* src = "fifo.v:8.32-8.45" *)
  output [5:0] fifo_data_out_synth;
  (* src = "fifo.v:13.12-13.22" *)
  output fifo_empty_synth;
  (* src = "fifo.v:12.12-12.21" *)
  output fifo_full_synth;
  (* src = "fifo.v:15.11-15.18" *)
  input fifo_rd;
  (* src = "fifo.v:14.11-14.18" *)
  input fifo_wr;
  (* src = "fifo.v:17.23-17.37" *)
  input [2:0] full_threshold;
  (* src = "fifo.v:25.8-25.11" *)
  wire pop;
  (* src = "fifo.v:26.8-26.12" *)
  wire push;
  (* src = "fifo.v:27.18-27.24" *)
  wire [2:0] rd_ptr;
  (* src = "fifo.v:20.11-20.18" *)
  input reset_L;
  (* src = "fifo.v:28.18-28.24" *)
  wire [2:0] wr_ptr;
  (* src = "fifo.v:79.1-82.4" *)
  DFF _00_ (
    .C(clk),
    .D(data_out_MM[0]),
    .Q(fifo_data_out_synth[0])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _01_ (
    .C(clk),
    .D(data_out_MM[1]),
    .Q(fifo_data_out_synth[1])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _02_ (
    .C(clk),
    .D(data_out_MM[2]),
    .Q(fifo_data_out_synth[2])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _03_ (
    .C(clk),
    .D(data_out_MM[3]),
    .Q(fifo_data_out_synth[3])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _04_ (
    .C(clk),
    .D(data_out_MM[4]),
    .Q(fifo_data_out_synth[4])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _05_ (
    .C(clk),
    .D(data_out_MM[5]),
    .Q(fifo_data_out_synth[5])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _06_ (
    .C(clk),
    .D(fifo_data_in[0]),
    .Q(data_in_MM[0])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _07_ (
    .C(clk),
    .D(fifo_data_in[1]),
    .Q(data_in_MM[1])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _08_ (
    .C(clk),
    .D(fifo_data_in[2]),
    .Q(data_in_MM[2])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _09_ (
    .C(clk),
    .D(fifo_data_in[3]),
    .Q(data_in_MM[3])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _10_ (
    .C(clk),
    .D(fifo_data_in[4]),
    .Q(data_in_MM[4])
  );
  (* src = "fifo.v:79.1-82.4" *)
  DFF _11_ (
    .C(clk),
    .D(fifo_data_in[5]),
    .Q(data_in_MM[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "fifo.v:51.15-64.26" *)
  control_logic_synth control_log (
    .almost_empty_synth(almost_empty_synth),
    .almost_full_synth(almost_full_synth),
    .clk(clk),
    .empty_threshold(empty_threshold),
    .error_synth(error_synth),
    .fifo_empty_synth(fifo_empty_synth),
    .fifo_full_synth(fifo_full_synth),
    .fifo_rd(fifo_rd),
    .fifo_wr(fifo_wr),
    .full_threshold(full_threshold),
    .reset_L(reset_L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "fifo.v:66.8-76.22" *)
  memory_synth memoria (
    .clk(clk),
    .data_in_MM(data_in_MM),
    .data_out_MM(data_out_MM),
    .pop(pop),
    .push(push),
    .rd_ptr(rd_ptr),
    .reset_L(reset_L),
    .wr_ptr(wr_ptr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "fifo.v:41.12-49.27" *)
  read_logic_synth read_log (
    .clk(clk),
    .fifo_empty_synth(fifo_empty_synth),
    .fifo_rd(fifo_rd),
    .pop(pop),
    .rd_ptr(rd_ptr),
    .reset_L(reset_L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "fifo.v:31.13-39.29" *)
  write_logic_synth write_log (
    .clk(clk),
    .fifo_full_synth(fifo_full_synth),
    .fifo_wr(fifo_wr),
    .push(push),
    .reset_L(reset_L),
    .wr_ptr(wr_ptr)
  );
endmodule

(* dynports =  1  *)
(* src = "memory_synth.v:1.1-43.10" *)
module memory_synth(rd_ptr, wr_ptr, data_in_MM, push, pop, reset_L, clk, data_out_MM);
  (* src = "memory_synth.v:19.1-41.4" *)
  wire [5:0] _000_;
  (* src = "memory_synth.v:19.1-41.4" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _001_;
  (* src = "memory_synth.v:19.1-41.4" *)
  wire [5:0] _002_;
  (* src = "memory_synth.v:19.1-41.4" *)
  wire [5:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _058_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _059_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _060_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _061_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _062_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  (* src = "memory_synth.v:11.11-11.14" *)
  wire _197_;
  (* src = "memory_synth.v:10.11-10.15" *)
  wire _198_;
  (* src = "memory_synth.v:7.23-7.29" *)
  wire _199_;
  (* src = "memory_synth.v:7.23-7.29" *)
  wire _200_;
  (* src = "memory_synth.v:12.11-12.18" *)
  wire _201_;
  (* src = "memory_synth.v:8.23-8.29" *)
  wire _202_;
  (* src = "memory_synth.v:8.23-8.29" *)
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire [5:0] _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire [1:0] _248_;
  wire [1:0] _249_;
  wire [1:0] _250_;
  wire [5:0] _251_;
  wire [5:0] _252_;
  wire _253_;
  wire [5:0] _254_;
  wire [5:0] _255_;
  wire [5:0] _256_;
  wire [5:0] _257_;
  (* src = "memory_synth.v:34.28-34.31" *)
  wire [5:0] _258_;
  wire [5:0] _259_;
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _260_;
  (* force_downto = 32'd1 *)
  (* src = "memory_synth.v:30.17-30.25|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "2" *)
  wire [31:0] _261_;
  (* force_downto = 32'd1 *)
  (* src = "memory_synth.v:30.17-30.25|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _262_;
  (* force_downto = 32'd1 *)
  (* src = "memory_synth.v:34.32-34.40|memory_synth.v:30.17-30.25|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "2" *)
  wire [31:0] _263_;
  (* force_downto = 32'd1 *)
  (* src = "memory_synth.v:34.32-34.40|memory_synth.v:30.17-30.25|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "0 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _264_;
  wire [5:0] \Mem[0] ;
  wire [5:0] \Mem[1] ;
  wire [5:0] \Mem[2] ;
  wire [5:0] \Mem[3] ;
  (* src = "memory_synth.v:13.11-13.14" *)
  input clk;
  (* src = "memory_synth.v:9.27-9.37" *)
  input [5:0] data_in_MM;
  (* src = "memory_synth.v:14.32-14.43" *)
  output [5:0] data_out_MM;
  (* src = "memory_synth.v:17.9-17.10" *)
  wire [31:0] i;
  (* src = "memory_synth.v:11.11-11.14" *)
  input pop;
  (* src = "memory_synth.v:10.11-10.15" *)
  input push;
  (* src = "memory_synth.v:7.23-7.29" *)
  input [2:0] rd_ptr;
  (* src = "memory_synth.v:12.11-12.18" *)
  input reset_L;
  (* src = "memory_synth.v:8.23-8.29" *)
  input [2:0] wr_ptr;
  NOT _265_ (
    .A(_015_),
    .Y(_166_)
  );
  NOT _266_ (
    .A(_014_),
    .Y(_167_)
  );
  NOT _267_ (
    .A(_013_),
    .Y(_168_)
  );
  NOT _268_ (
    .A(_012_),
    .Y(_169_)
  );
  NOT _269_ (
    .A(_011_),
    .Y(_170_)
  );
  NOT _270_ (
    .A(_010_),
    .Y(_171_)
  );
  NOT _271_ (
    .A(_203_),
    .Y(_172_)
  );
  NOT _272_ (
    .A(_200_),
    .Y(_173_)
  );
  NOT _273_ (
    .A(_201_),
    .Y(_174_)
  );
  NOT _274_ (
    .A(_199_),
    .Y(_175_)
  );
  NOT _275_ (
    .A(_198_),
    .Y(_176_)
  );
  NAND _276_ (
    .A(_201_),
    .B(_197_),
    .Y(_177_)
  );
  NOR _277_ (
    .A(_200_),
    .B(_199_),
    .Y(_178_)
  );
  NOT _278_ (
    .A(_178_),
    .Y(_179_)
  );
  NOR _279_ (
    .A(_173_),
    .B(_175_),
    .Y(_180_)
  );
  NAND _280_ (
    .A(_200_),
    .B(_199_),
    .Y(_181_)
  );
  NAND _281_ (
    .A(_179_),
    .B(_181_),
    .Y(_182_)
  );
  NOR _282_ (
    .A(_167_),
    .B(_199_),
    .Y(_183_)
  );
  NAND _283_ (
    .A(_008_),
    .B(_199_),
    .Y(_184_)
  );
  NOT _284_ (
    .A(_184_),
    .Y(_185_)
  );
  NOR _285_ (
    .A(_183_),
    .B(_185_),
    .Y(_186_)
  );
  NOR _286_ (
    .A(_182_),
    .B(_186_),
    .Y(_187_)
  );
  NAND _287_ (
    .A(_026_),
    .B(_178_),
    .Y(_188_)
  );
  NAND _288_ (
    .A(_020_),
    .B(_180_),
    .Y(_189_)
  );
  NAND _289_ (
    .A(_188_),
    .B(_189_),
    .Y(_190_)
  );
  NOR _290_ (
    .A(_187_),
    .B(_190_),
    .Y(_191_)
  );
  NOR _291_ (
    .A(_177_),
    .B(_191_),
    .Y(_056_)
  );
  NOR _292_ (
    .A(_168_),
    .B(_199_),
    .Y(_192_)
  );
  NAND _293_ (
    .A(_007_),
    .B(_199_),
    .Y(_193_)
  );
  NOT _294_ (
    .A(_193_),
    .Y(_194_)
  );
  NOR _295_ (
    .A(_192_),
    .B(_194_),
    .Y(_195_)
  );
  NOR _296_ (
    .A(_182_),
    .B(_195_),
    .Y(_196_)
  );
  NAND _297_ (
    .A(_019_),
    .B(_180_),
    .Y(_064_)
  );
  NAND _298_ (
    .A(_025_),
    .B(_178_),
    .Y(_065_)
  );
  NAND _299_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _300_ (
    .A(_196_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _301_ (
    .A(_177_),
    .B(_067_),
    .Y(_055_)
  );
  NOR _302_ (
    .A(_169_),
    .B(_199_),
    .Y(_068_)
  );
  NAND _303_ (
    .A(_006_),
    .B(_199_),
    .Y(_069_)
  );
  NOT _304_ (
    .A(_069_),
    .Y(_070_)
  );
  NOR _305_ (
    .A(_068_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _306_ (
    .A(_182_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _307_ (
    .A(_018_),
    .B(_180_),
    .Y(_073_)
  );
  NAND _308_ (
    .A(_024_),
    .B(_178_),
    .Y(_074_)
  );
  NAND _309_ (
    .A(_073_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _310_ (
    .A(_072_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _311_ (
    .A(_177_),
    .B(_076_),
    .Y(_054_)
  );
  NOR _312_ (
    .A(_170_),
    .B(_199_),
    .Y(_077_)
  );
  NAND _313_ (
    .A(_005_),
    .B(_199_),
    .Y(_078_)
  );
  NOT _314_ (
    .A(_078_),
    .Y(_079_)
  );
  NOR _315_ (
    .A(_077_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _316_ (
    .A(_182_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _317_ (
    .A(_017_),
    .B(_180_),
    .Y(_082_)
  );
  NAND _318_ (
    .A(_023_),
    .B(_178_),
    .Y(_083_)
  );
  NAND _319_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  NOR _320_ (
    .A(_081_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _321_ (
    .A(_177_),
    .B(_085_),
    .Y(_053_)
  );
  NOR _322_ (
    .A(_171_),
    .B(_199_),
    .Y(_086_)
  );
  NAND _323_ (
    .A(_004_),
    .B(_199_),
    .Y(_087_)
  );
  NOT _324_ (
    .A(_087_),
    .Y(_088_)
  );
  NOR _325_ (
    .A(_086_),
    .B(_088_),
    .Y(_089_)
  );
  NOR _326_ (
    .A(_182_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _327_ (
    .A(_016_),
    .B(_180_),
    .Y(_091_)
  );
  NAND _328_ (
    .A(_022_),
    .B(_178_),
    .Y(_092_)
  );
  NAND _329_ (
    .A(_091_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _330_ (
    .A(_090_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _331_ (
    .A(_177_),
    .B(_094_),
    .Y(_052_)
  );
  NOR _332_ (
    .A(_174_),
    .B(_176_),
    .Y(_095_)
  );
  NAND _333_ (
    .A(_202_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _334_ (
    .A(_203_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _335_ (
    .A(_174_),
    .B(_097_),
    .Y(_098_)
  );
  NAND _336_ (
    .A(_009_),
    .B(_098_),
    .Y(_099_)
  );
  NAND _337_ (
    .A(_063_),
    .B(_097_),
    .Y(_100_)
  );
  NAND _338_ (
    .A(_099_),
    .B(_100_),
    .Y(_051_)
  );
  NAND _339_ (
    .A(_008_),
    .B(_098_),
    .Y(_101_)
  );
  NAND _340_ (
    .A(_062_),
    .B(_097_),
    .Y(_102_)
  );
  NAND _341_ (
    .A(_101_),
    .B(_102_),
    .Y(_050_)
  );
  NAND _342_ (
    .A(_007_),
    .B(_098_),
    .Y(_103_)
  );
  NAND _343_ (
    .A(_061_),
    .B(_097_),
    .Y(_104_)
  );
  NAND _344_ (
    .A(_103_),
    .B(_104_),
    .Y(_049_)
  );
  NAND _345_ (
    .A(_006_),
    .B(_098_),
    .Y(_105_)
  );
  NAND _346_ (
    .A(_060_),
    .B(_097_),
    .Y(_106_)
  );
  NAND _347_ (
    .A(_105_),
    .B(_106_),
    .Y(_048_)
  );
  NAND _348_ (
    .A(_005_),
    .B(_098_),
    .Y(_107_)
  );
  NAND _349_ (
    .A(_059_),
    .B(_097_),
    .Y(_108_)
  );
  NAND _350_ (
    .A(_107_),
    .B(_108_),
    .Y(_047_)
  );
  NAND _351_ (
    .A(_004_),
    .B(_098_),
    .Y(_109_)
  );
  NAND _352_ (
    .A(_058_),
    .B(_097_),
    .Y(_110_)
  );
  NAND _353_ (
    .A(_109_),
    .B(_110_),
    .Y(_046_)
  );
  NAND _354_ (
    .A(_203_),
    .B(_095_),
    .Y(_111_)
  );
  NOR _355_ (
    .A(_202_),
    .B(_111_),
    .Y(_112_)
  );
  NOR _356_ (
    .A(_174_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _357_ (
    .A(_015_),
    .B(_113_),
    .Y(_114_)
  );
  NAND _358_ (
    .A(_063_),
    .B(_112_),
    .Y(_115_)
  );
  NAND _359_ (
    .A(_114_),
    .B(_115_),
    .Y(_045_)
  );
  NAND _360_ (
    .A(_014_),
    .B(_113_),
    .Y(_116_)
  );
  NAND _361_ (
    .A(_062_),
    .B(_112_),
    .Y(_117_)
  );
  NAND _362_ (
    .A(_116_),
    .B(_117_),
    .Y(_044_)
  );
  NAND _363_ (
    .A(_013_),
    .B(_113_),
    .Y(_118_)
  );
  NAND _364_ (
    .A(_061_),
    .B(_112_),
    .Y(_119_)
  );
  NAND _365_ (
    .A(_118_),
    .B(_119_),
    .Y(_043_)
  );
  NAND _366_ (
    .A(_012_),
    .B(_113_),
    .Y(_120_)
  );
  NAND _367_ (
    .A(_060_),
    .B(_112_),
    .Y(_121_)
  );
  NAND _368_ (
    .A(_120_),
    .B(_121_),
    .Y(_042_)
  );
  NAND _369_ (
    .A(_011_),
    .B(_113_),
    .Y(_122_)
  );
  NAND _370_ (
    .A(_059_),
    .B(_112_),
    .Y(_123_)
  );
  NAND _371_ (
    .A(_122_),
    .B(_123_),
    .Y(_041_)
  );
  NAND _372_ (
    .A(_010_),
    .B(_113_),
    .Y(_124_)
  );
  NAND _373_ (
    .A(_058_),
    .B(_112_),
    .Y(_125_)
  );
  NAND _374_ (
    .A(_124_),
    .B(_125_),
    .Y(_040_)
  );
  NOR _375_ (
    .A(_172_),
    .B(_096_),
    .Y(_126_)
  );
  NOR _376_ (
    .A(_174_),
    .B(_126_),
    .Y(_127_)
  );
  NAND _377_ (
    .A(_021_),
    .B(_127_),
    .Y(_128_)
  );
  NAND _378_ (
    .A(_063_),
    .B(_126_),
    .Y(_129_)
  );
  NAND _379_ (
    .A(_128_),
    .B(_129_),
    .Y(_039_)
  );
  NAND _380_ (
    .A(_020_),
    .B(_127_),
    .Y(_130_)
  );
  NAND _381_ (
    .A(_062_),
    .B(_126_),
    .Y(_131_)
  );
  NAND _382_ (
    .A(_130_),
    .B(_131_),
    .Y(_038_)
  );
  NAND _383_ (
    .A(_019_),
    .B(_127_),
    .Y(_132_)
  );
  NAND _384_ (
    .A(_061_),
    .B(_126_),
    .Y(_133_)
  );
  NAND _385_ (
    .A(_132_),
    .B(_133_),
    .Y(_037_)
  );
  NAND _386_ (
    .A(_018_),
    .B(_127_),
    .Y(_134_)
  );
  NAND _387_ (
    .A(_060_),
    .B(_126_),
    .Y(_135_)
  );
  NAND _388_ (
    .A(_134_),
    .B(_135_),
    .Y(_036_)
  );
  NAND _389_ (
    .A(_017_),
    .B(_127_),
    .Y(_136_)
  );
  NAND _390_ (
    .A(_059_),
    .B(_126_),
    .Y(_137_)
  );
  NAND _391_ (
    .A(_136_),
    .B(_137_),
    .Y(_035_)
  );
  NAND _392_ (
    .A(_016_),
    .B(_127_),
    .Y(_138_)
  );
  NAND _393_ (
    .A(_058_),
    .B(_126_),
    .Y(_139_)
  );
  NAND _394_ (
    .A(_138_),
    .B(_139_),
    .Y(_034_)
  );
  NOR _395_ (
    .A(_203_),
    .B(_202_),
    .Y(_140_)
  );
  NAND _396_ (
    .A(_198_),
    .B(_140_),
    .Y(_141_)
  );
  NOT _397_ (
    .A(_141_),
    .Y(_142_)
  );
  NOR _398_ (
    .A(_174_),
    .B(_142_),
    .Y(_143_)
  );
  NAND _399_ (
    .A(_027_),
    .B(_143_),
    .Y(_144_)
  );
  NOR _400_ (
    .A(_174_),
    .B(_141_),
    .Y(_145_)
  );
  NAND _401_ (
    .A(_063_),
    .B(_145_),
    .Y(_146_)
  );
  NAND _402_ (
    .A(_144_),
    .B(_146_),
    .Y(_033_)
  );
  NAND _403_ (
    .A(_026_),
    .B(_143_),
    .Y(_147_)
  );
  NAND _404_ (
    .A(_062_),
    .B(_145_),
    .Y(_148_)
  );
  NAND _405_ (
    .A(_147_),
    .B(_148_),
    .Y(_032_)
  );
  NAND _406_ (
    .A(_025_),
    .B(_143_),
    .Y(_149_)
  );
  NAND _407_ (
    .A(_061_),
    .B(_145_),
    .Y(_150_)
  );
  NAND _408_ (
    .A(_149_),
    .B(_150_),
    .Y(_031_)
  );
  NAND _409_ (
    .A(_024_),
    .B(_143_),
    .Y(_151_)
  );
  NAND _410_ (
    .A(_060_),
    .B(_145_),
    .Y(_152_)
  );
  NAND _411_ (
    .A(_151_),
    .B(_152_),
    .Y(_030_)
  );
  NAND _412_ (
    .A(_023_),
    .B(_143_),
    .Y(_153_)
  );
  NAND _413_ (
    .A(_059_),
    .B(_145_),
    .Y(_154_)
  );
  NAND _414_ (
    .A(_153_),
    .B(_154_),
    .Y(_029_)
  );
  NAND _415_ (
    .A(_022_),
    .B(_143_),
    .Y(_155_)
  );
  NAND _416_ (
    .A(_058_),
    .B(_145_),
    .Y(_156_)
  );
  NAND _417_ (
    .A(_155_),
    .B(_156_),
    .Y(_028_)
  );
  NOR _418_ (
    .A(_166_),
    .B(_199_),
    .Y(_157_)
  );
  NAND _419_ (
    .A(_009_),
    .B(_199_),
    .Y(_158_)
  );
  NOT _420_ (
    .A(_158_),
    .Y(_159_)
  );
  NOR _421_ (
    .A(_157_),
    .B(_159_),
    .Y(_160_)
  );
  NOR _422_ (
    .A(_182_),
    .B(_160_),
    .Y(_161_)
  );
  NAND _423_ (
    .A(_021_),
    .B(_180_),
    .Y(_162_)
  );
  NAND _424_ (
    .A(_027_),
    .B(_178_),
    .Y(_163_)
  );
  NAND _425_ (
    .A(_162_),
    .B(_163_),
    .Y(_164_)
  );
  NOR _426_ (
    .A(_161_),
    .B(_164_),
    .Y(_165_)
  );
  NOR _427_ (
    .A(_177_),
    .B(_165_),
    .Y(_057_)
  );
  DFF _428_ (
    .C(clk),
    .D(_218_),
    .Q(\Mem[3] [0])
  );
  DFF _429_ (
    .C(clk),
    .D(_219_),
    .Q(\Mem[3] [1])
  );
  DFF _430_ (
    .C(clk),
    .D(_220_),
    .Q(\Mem[3] [2])
  );
  DFF _431_ (
    .C(clk),
    .D(_221_),
    .Q(\Mem[3] [3])
  );
  DFF _432_ (
    .C(clk),
    .D(_222_),
    .Q(\Mem[3] [4])
  );
  DFF _433_ (
    .C(clk),
    .D(_223_),
    .Q(\Mem[3] [5])
  );
  DFF _434_ (
    .C(clk),
    .D(_224_),
    .Q(\Mem[2] [0])
  );
  DFF _435_ (
    .C(clk),
    .D(_225_),
    .Q(\Mem[2] [1])
  );
  DFF _436_ (
    .C(clk),
    .D(_226_),
    .Q(\Mem[2] [2])
  );
  DFF _437_ (
    .C(clk),
    .D(_227_),
    .Q(\Mem[2] [3])
  );
  DFF _438_ (
    .C(clk),
    .D(_228_),
    .Q(\Mem[2] [4])
  );
  DFF _439_ (
    .C(clk),
    .D(_229_),
    .Q(\Mem[2] [5])
  );
  DFF _440_ (
    .C(clk),
    .D(_230_),
    .Q(\Mem[1] [0])
  );
  DFF _441_ (
    .C(clk),
    .D(_231_),
    .Q(\Mem[1] [1])
  );
  DFF _442_ (
    .C(clk),
    .D(_232_),
    .Q(\Mem[1] [2])
  );
  DFF _443_ (
    .C(clk),
    .D(_233_),
    .Q(\Mem[1] [3])
  );
  DFF _444_ (
    .C(clk),
    .D(_234_),
    .Q(\Mem[1] [4])
  );
  DFF _445_ (
    .C(clk),
    .D(_235_),
    .Q(\Mem[1] [5])
  );
  DFF _446_ (
    .C(clk),
    .D(_236_),
    .Q(\Mem[0] [0])
  );
  DFF _447_ (
    .C(clk),
    .D(_237_),
    .Q(\Mem[0] [1])
  );
  DFF _448_ (
    .C(clk),
    .D(_238_),
    .Q(\Mem[0] [2])
  );
  DFF _449_ (
    .C(clk),
    .D(_239_),
    .Q(\Mem[0] [3])
  );
  DFF _450_ (
    .C(clk),
    .D(_240_),
    .Q(\Mem[0] [4])
  );
  DFF _451_ (
    .C(clk),
    .D(_241_),
    .Q(\Mem[0] [5])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _452_ (
    .C(clk),
    .D(_242_),
    .Q(data_out_MM[0])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _453_ (
    .C(clk),
    .D(_243_),
    .Q(data_out_MM[1])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _454_ (
    .C(clk),
    .D(_244_),
    .Q(data_out_MM[2])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _455_ (
    .C(clk),
    .D(_245_),
    .Q(data_out_MM[3])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _456_ (
    .C(clk),
    .D(_246_),
    .Q(data_out_MM[4])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _457_ (
    .C(clk),
    .D(_247_),
    .Q(data_out_MM[5])
  );
  assign _000_[4:0] = { _000_[5], _000_[5], _000_[5], _000_[5], _000_[5] };
  assign _001_[30:3] = { _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31], _001_[31] };
  assign _003_[4:0] = { _003_[5], _003_[5], _003_[5], _003_[5], _003_[5] };
  assign _248_[0] = _000_[5];
  assign _249_[0] = _000_[5];
  assign _250_[0] = _000_[5];
  assign _254_[4:0] = { _254_[5], _254_[5], _254_[5], _254_[5], _254_[5] };
  assign _260_[30:3] = { _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31], _260_[31] };
  assign { _261_[31:3], _261_[0] } = { 29'h1fffffff, wr_ptr[0] };
  assign _262_[30:3] = { _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31], _262_[31] };
  assign { _263_[31:3], _263_[0] } = { 29'h1fffffff, rd_ptr[0] };
  assign _264_[30:3] = { _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31], _264_[31] };
  assign i = 32'd4;
  assign _246_ = _056_;
  assign _245_ = _055_;
  assign _244_ = _054_;
  assign _243_ = _053_;
  assign _242_ = _052_;
  assign _009_ = \Mem[0] [5];
  assign _241_ = _051_;
  assign _008_ = \Mem[0] [4];
  assign _240_ = _050_;
  assign _007_ = \Mem[0] [3];
  assign _239_ = _049_;
  assign _006_ = \Mem[0] [2];
  assign _238_ = _048_;
  assign _005_ = \Mem[0] [1];
  assign _237_ = _047_;
  assign _004_ = \Mem[0] [0];
  assign _236_ = _046_;
  assign _015_ = \Mem[1] [5];
  assign _235_ = _045_;
  assign _014_ = \Mem[1] [4];
  assign _234_ = _044_;
  assign _013_ = \Mem[1] [3];
  assign _233_ = _043_;
  assign _012_ = \Mem[1] [2];
  assign _232_ = _042_;
  assign _011_ = \Mem[1] [1];
  assign _231_ = _041_;
  assign _010_ = \Mem[1] [0];
  assign _230_ = _040_;
  assign _021_ = \Mem[2] [5];
  assign _229_ = _039_;
  assign _020_ = \Mem[2] [4];
  assign _228_ = _038_;
  assign _019_ = \Mem[2] [3];
  assign _227_ = _037_;
  assign _018_ = \Mem[2] [2];
  assign _226_ = _036_;
  assign _017_ = \Mem[2] [1];
  assign _225_ = _035_;
  assign _016_ = \Mem[2] [0];
  assign _224_ = _034_;
  assign _027_ = \Mem[3] [5];
  assign _223_ = _033_;
  assign _026_ = \Mem[3] [4];
  assign _222_ = _032_;
  assign _025_ = \Mem[3] [3];
  assign _221_ = _031_;
  assign _024_ = \Mem[3] [2];
  assign _220_ = _030_;
  assign _023_ = \Mem[3] [1];
  assign _219_ = _029_;
  assign _022_ = \Mem[3] [0];
  assign _218_ = _028_;
  assign _203_ = wr_ptr[1];
  assign _202_ = wr_ptr[0];
  assign _200_ = rd_ptr[1];
  assign _201_ = reset_L;
  assign _197_ = pop;
  assign _199_ = rd_ptr[0];
  assign _198_ = push;
  assign _058_ = data_in_MM[0];
  assign _059_ = data_in_MM[1];
  assign _060_ = data_in_MM[2];
  assign _061_ = data_in_MM[3];
  assign _062_ = data_in_MM[4];
  assign _063_ = data_in_MM[5];
  assign _247_ = _057_;
endmodule

(* dynports =  1  *)
(* src = "read_logic_synth.v:1.1-35.10" *)
module read_logic_synth(fifo_rd, fifo_empty_synth, clk, reset_L, rd_ptr, pop);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "read_logic_synth.v:9.11-9.21" *)
  wire _04_;
  (* src = "read_logic_synth.v:8.11-8.18" *)
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "read_logic_synth.v:12.28-12.34" *)
  wire _17_;
  (* src = "read_logic_synth.v:12.28-12.34" *)
  wire _18_;
  (* src = "read_logic_synth.v:12.28-12.34" *)
  wire _19_;
  (* src = "read_logic_synth.v:11.11-11.18" *)
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  (* src = "read_logic_synth.v:22.13-22.35" *)
  wire _31_;
  (* src = "read_logic_synth.v:22.24-22.35" *)
  wire _32_;
  wire [2:0] _33_;
  (* force_downto = 32'd1 *)
  (* src = "read_logic_synth.v:24.23-24.33|write_logic_synth.v:24.23-24.33|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _34_;
  (* force_downto = 32'd1 *)
  (* src = "read_logic_synth.v:24.23-24.33|write_logic_synth.v:24.23-24.33|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _35_;
  (* force_downto = 32'd1 *)
  (* src = "read_logic_synth.v:24.23-24.33|write_logic_synth.v:24.23-24.33|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [31:0] _36_;
  (* src = "read_logic_synth.v:10.11-10.14" *)
  input clk;
  (* src = "read_logic_synth.v:9.11-9.21" *)
  input fifo_empty_synth;
  (* src = "read_logic_synth.v:8.11-8.18" *)
  input fifo_rd;
  (* src = "read_logic_synth.v:13.16-13.19" *)
  output pop;
  (* src = "read_logic_synth.v:12.28-12.34" *)
  output [2:0] rd_ptr;
  (* src = "read_logic_synth.v:11.11-11.18" *)
  input reset_L;
  NOT _37_ (
    .A(_19_),
    .Y(_06_)
  );
  NOT _38_ (
    .A(_20_),
    .Y(_07_)
  );
  NOT _39_ (
    .A(_17_),
    .Y(_08_)
  );
  NOT _40_ (
    .A(_04_),
    .Y(_09_)
  );
  NAND _41_ (
    .A(_09_),
    .B(_05_),
    .Y(_10_)
  );
  NOR _42_ (
    .A(_08_),
    .B(_10_),
    .Y(_11_)
  );
  NOR _43_ (
    .A(_18_),
    .B(_11_),
    .Y(_12_)
  );
  NAND _44_ (
    .A(_18_),
    .B(_11_),
    .Y(_13_)
  );
  NAND _45_ (
    .A(_20_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _46_ (
    .A(_12_),
    .B(_14_),
    .Y(_02_)
  );
  NAND _47_ (
    .A(_08_),
    .B(_10_),
    .Y(_15_)
  );
  NAND _48_ (
    .A(_20_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _49_ (
    .A(_11_),
    .B(_16_),
    .Y(_01_)
  );
  NOR _50_ (
    .A(_07_),
    .B(_10_),
    .Y(_00_)
  );
  NOR _51_ (
    .A(_06_),
    .B(_14_),
    .Y(_03_)
  );
  (* src = "read_logic_synth.v:16.1-33.4" *)
  DFF _52_ (
    .C(clk),
    .D(_22_),
    .Q(pop)
  );
  (* src = "read_logic_synth.v:16.1-33.4" *)
  DFF _53_ (
    .C(clk),
    .D(_24_),
    .Q(rd_ptr[0])
  );
  (* src = "read_logic_synth.v:16.1-33.4" *)
  DFF _54_ (
    .C(clk),
    .D(_26_),
    .Q(rd_ptr[1])
  );
  (* src = "read_logic_synth.v:16.1-33.4" *)
  DFF _55_ (
    .C(clk),
    .D(_28_),
    .Q(rd_ptr[2])
  );
  assign { _34_[31:3], _34_[0] } = { 29'h00000000, rd_ptr[0] };
  assign _35_[31:1] = { 29'h00000000, rd_ptr[2:1] };
  assign { _36_[31:3], _36_[0] } = { 28'h0000000, _34_[2], _35_[0] };
  assign _19_ = rd_ptr[2];
  assign _20_ = reset_L;
  assign _26_ = _02_;
  assign _18_ = rd_ptr[1];
  assign _24_ = _01_;
  assign _17_ = rd_ptr[0];
  assign _22_ = _00_;
  assign _04_ = fifo_empty_synth;
  assign _05_ = fifo_rd;
  assign _28_ = _03_;
endmodule

(* dynports =  1  *)
(* src = "write_logic_synth.v:1.1-35.10" *)
module write_logic_synth(fifo_wr, fifo_full_synth, clk, reset_L, wr_ptr, push);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "write_logic_synth.v:9.11-9.20" *)
  wire _04_;
  (* src = "write_logic_synth.v:8.11-8.18" *)
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "write_logic_synth.v:11.11-11.18" *)
  wire _17_;
  (* src = "write_logic_synth.v:12.28-12.34" *)
  wire _18_;
  (* src = "write_logic_synth.v:12.28-12.34" *)
  wire _19_;
  (* src = "write_logic_synth.v:12.28-12.34" *)
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  (* src = "write_logic_synth.v:22.13-22.34" *)
  wire _31_;
  (* src = "write_logic_synth.v:22.24-22.34" *)
  wire _32_;
  wire [2:0] _33_;
  (* force_downto = 32'd1 *)
  (* src = "write_logic_synth.v:24.23-24.33|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _34_;
  (* force_downto = 32'd1 *)
  (* src = "write_logic_synth.v:24.23-24.33|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _35_;
  (* force_downto = 32'd1 *)
  (* src = "write_logic_synth.v:24.23-24.33|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [31:0] _36_;
  (* src = "write_logic_synth.v:10.11-10.14" *)
  input clk;
  (* src = "write_logic_synth.v:9.11-9.20" *)
  input fifo_full_synth;
  (* src = "write_logic_synth.v:8.11-8.18" *)
  input fifo_wr;
  (* src = "write_logic_synth.v:13.16-13.20" *)
  output push;
  (* src = "write_logic_synth.v:11.11-11.18" *)
  input reset_L;
  (* src = "write_logic_synth.v:12.28-12.34" *)
  output [2:0] wr_ptr;
  NOT _37_ (
    .A(_20_),
    .Y(_06_)
  );
  NOT _38_ (
    .A(_17_),
    .Y(_07_)
  );
  NOT _39_ (
    .A(_18_),
    .Y(_08_)
  );
  NOT _40_ (
    .A(_04_),
    .Y(_09_)
  );
  NAND _41_ (
    .A(_09_),
    .B(_05_),
    .Y(_10_)
  );
  NOR _42_ (
    .A(_08_),
    .B(_10_),
    .Y(_11_)
  );
  NOR _43_ (
    .A(_19_),
    .B(_11_),
    .Y(_12_)
  );
  NAND _44_ (
    .A(_19_),
    .B(_11_),
    .Y(_13_)
  );
  NAND _45_ (
    .A(_17_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _46_ (
    .A(_12_),
    .B(_14_),
    .Y(_02_)
  );
  NAND _47_ (
    .A(_08_),
    .B(_10_),
    .Y(_15_)
  );
  NAND _48_ (
    .A(_17_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _49_ (
    .A(_11_),
    .B(_16_),
    .Y(_01_)
  );
  NOR _50_ (
    .A(_07_),
    .B(_10_),
    .Y(_00_)
  );
  NOR _51_ (
    .A(_06_),
    .B(_14_),
    .Y(_03_)
  );
  (* src = "write_logic_synth.v:16.1-33.4" *)
  DFF _52_ (
    .C(clk),
    .D(_22_),
    .Q(push)
  );
  (* src = "write_logic_synth.v:16.1-33.4" *)
  DFF _53_ (
    .C(clk),
    .D(_24_),
    .Q(wr_ptr[0])
  );
  (* src = "write_logic_synth.v:16.1-33.4" *)
  DFF _54_ (
    .C(clk),
    .D(_26_),
    .Q(wr_ptr[1])
  );
  (* src = "write_logic_synth.v:16.1-33.4" *)
  DFF _55_ (
    .C(clk),
    .D(_28_),
    .Q(wr_ptr[2])
  );
  assign { _34_[31:3], _34_[0] } = { 29'h00000000, wr_ptr[0] };
  assign _35_[31:1] = { 29'h00000000, wr_ptr[2:1] };
  assign { _36_[31:3], _36_[0] } = { 28'h0000000, _34_[2], _35_[0] };
  assign _20_ = wr_ptr[2];
  assign _17_ = reset_L;
  assign _26_ = _02_;
  assign _19_ = wr_ptr[1];
  assign _24_ = _01_;
  assign _18_ = wr_ptr[0];
  assign _22_ = _00_;
  assign _04_ = fifo_full_synth;
  assign _05_ = fifo_wr;
  assign _28_ = _03_;
endmodule
