/* Generated by Yosys 0.9+3565 (git sha1 474cd02e, gcc 9.3.0-10ubuntu2 -fPIC -Os) */

(* dynports =  1  *)
(* src = "control_logic_synth.v:1.1-90.10" *)
module control_logic_synth(full_threshold, empty_threshold, fifo_rd, fifo_wr, clk, reset_L, error_synth, almost_empty_synth, almost_full_synth, fifo_full_synth, fifo_empty_synth);
  (* src = "control_logic_synth.v:15.16-15.28" *)
  wire _000_;
  (* src = "control_logic_synth.v:16.16-16.27" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire _008_;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire _009_;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire _010_;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  wire _011_;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  wire _012_;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  wire _013_;
  (* src = "control_logic_synth.v:14.16-14.21" *)
  wire _014_;
  (* src = "control_logic_synth.v:18.16-18.26" *)
  wire _015_;
  (* src = "control_logic_synth.v:17.16-17.25" *)
  wire _016_;
  (* src = "control_logic_synth.v:10.11-10.18" *)
  wire _017_;
  (* src = "control_logic_synth.v:11.11-11.18" *)
  wire _018_;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  wire _019_;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  wire _020_;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  (* src = "control_logic_synth.v:13.11-13.18" *)
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire [1:0] _139_;
  wire _140_;
  wire [1:0] _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire [15:0] _148_;
  wire [7:0] _149_;
  wire [2:0] _150_;
  wire [1:0] _151_;
  wire [3:0] _152_;
  wire [2:0] _153_;
  (* src = "control_logic_synth.v:26.13-26.38" *)
  wire _154_;
  (* src = "control_logic_synth.v:34.13-34.39" *)
  wire _155_;
  (* src = "control_logic_synth.v:60.14-60.33" *)
  wire _156_;
  (* src = "control_logic_synth.v:60.14-60.46" *)
  wire _157_;
  (* src = "control_logic_synth.v:60.52-60.71" *)
  wire _158_;
  (* src = "control_logic_synth.v:60.52-60.85" *)
  wire _159_;
  (* src = "control_logic_synth.v:73.18-73.51" *)
  wire _160_;
  (* src = "control_logic_synth.v:83.18-83.36" *)
  wire _161_;
  (* src = "control_logic_synth.v:83.18-83.49" *)
  wire _162_;
  (* src = "control_logic_synth.v:60.13-60.86" *)
  wire _163_;
  (* src = "control_logic_synth.v:60.25-60.33" *)
  wire _164_;
  (* src = "control_logic_synth.v:60.63-60.71" *)
  wire _165_;
  (* src = "control_logic_synth.v:63.41-63.52" *)
  wire _166_;
  (* src = "control_logic_synth.v:73.41-73.51" *)
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire [2:0] _177_;
  wire [2:0] _178_;
  wire [2:0] _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:74.24-74.35|write_logic_synth.v:38.23-38.33|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _184_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:74.24-74.35|write_logic_synth.v:38.23-38.33|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _185_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:74.24-74.35|write_logic_synth.v:38.23-38.33|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [31:0] _186_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [2:0] _187_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [2:0] _188_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _189_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [2:0] _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:79.22-79.34|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _195_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [2:0] _196_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [2:0] _197_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _198_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [2:0] _199_;
  wire _200_;
  wire _201_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:69.22-69.43|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [31:0] _202_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:69.22-69.43|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "2" *)
  wire [31:0] _203_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:84.24-84.35|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _204_;
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _205_;
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _206_;
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _207_;
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _208_;
  (* src = "control_logic_synth.v:15.16-15.28" *)
  output almost_empty_synth;
  (* src = "control_logic_synth.v:16.16-16.27" *)
  output almost_full_synth;
  (* src = "control_logic_synth.v:12.11-12.14" *)
  input clk;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire [2:0] counter;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  input [2:0] empty_threshold;
  (* src = "control_logic_synth.v:14.16-14.21" *)
  output error_synth;
  (* src = "control_logic_synth.v:18.16-18.26" *)
  output fifo_empty_synth;
  (* src = "control_logic_synth.v:17.16-17.25" *)
  output fifo_full_synth;
  (* src = "control_logic_synth.v:10.11-10.18" *)
  input fifo_rd;
  (* src = "control_logic_synth.v:11.11-11.18" *)
  input fifo_wr;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  input [2:0] full_threshold;
  (* src = "control_logic_synth.v:13.11-13.18" *)
  input reset_L;
  NOT _209_ (
    .A(_010_),
    .Y(_039_)
  );
  NOT _210_ (
    .A(_109_),
    .Y(_040_)
  );
  NOT _211_ (
    .A(_009_),
    .Y(_041_)
  );
  NOT _212_ (
    .A(_008_),
    .Y(_042_)
  );
  NOT _213_ (
    .A(_016_),
    .Y(_043_)
  );
  NOT _214_ (
    .A(_015_),
    .Y(_044_)
  );
  NOT _215_ (
    .A(_017_),
    .Y(_045_)
  );
  NOT _216_ (
    .A(_018_),
    .Y(_046_)
  );
  NOT _217_ (
    .A(_021_),
    .Y(_047_)
  );
  NOT _218_ (
    .A(_013_),
    .Y(_048_)
  );
  NAND _219_ (
    .A(_009_),
    .B(_008_),
    .Y(_049_)
  );
  NOR _220_ (
    .A(_009_),
    .B(_008_),
    .Y(_050_)
  );
  NOT _221_ (
    .A(_050_),
    .Y(_051_)
  );
  NAND _222_ (
    .A(_049_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _223_ (
    .A(_045_),
    .B(_018_),
    .Y(_053_)
  );
  NAND _224_ (
    .A(_017_),
    .B(_046_),
    .Y(_054_)
  );
  NOR _225_ (
    .A(_015_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _226_ (
    .A(_044_),
    .B(_053_),
    .Y(_056_)
  );
  NOR _227_ (
    .A(_043_),
    .B(_045_),
    .Y(_057_)
  );
  NAND _228_ (
    .A(_018_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _229_ (
    .A(_056_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _230_ (
    .A(_052_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _231_ (
    .A(_017_),
    .B(_046_),
    .Y(_061_)
  );
  NAND _232_ (
    .A(_045_),
    .B(_018_),
    .Y(_062_)
  );
  NOR _233_ (
    .A(_016_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _234_ (
    .A(_043_),
    .B(_061_),
    .Y(_064_)
  );
  NOR _235_ (
    .A(_055_),
    .B(_063_),
    .Y(_065_)
  );
  NOR _236_ (
    .A(_059_),
    .B(_063_),
    .Y(_066_)
  );
  NAND _237_ (
    .A(_058_),
    .B(_065_),
    .Y(_067_)
  );
  NAND _238_ (
    .A(_049_),
    .B(_063_),
    .Y(_068_)
  );
  NAND _239_ (
    .A(_067_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _240_ (
    .A(_009_),
    .B(_063_),
    .Y(_070_)
  );
  NOR _241_ (
    .A(_050_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _242_ (
    .A(_069_),
    .B(_071_),
    .Y(_072_)
  );
  NAND _243_ (
    .A(_060_),
    .B(_072_),
    .Y(_073_)
  );
  NAND _244_ (
    .A(_109_),
    .B(_073_),
    .Y(_074_)
  );
  NOT _245_ (
    .A(_074_),
    .Y(_006_)
  );
  NOR _246_ (
    .A(_008_),
    .B(_066_),
    .Y(_075_)
  );
  NOR _247_ (
    .A(_042_),
    .B(_067_),
    .Y(_076_)
  );
  NOR _248_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _249_ (
    .A(_040_),
    .B(_077_),
    .Y(_005_)
  );
  NAND _250_ (
    .A(_015_),
    .B(_053_),
    .Y(_078_)
  );
  NAND _251_ (
    .A(_016_),
    .B(_061_),
    .Y(_079_)
  );
  NAND _252_ (
    .A(_078_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _253_ (
    .A(_014_),
    .B(_054_),
    .Y(_081_)
  );
  NOR _254_ (
    .A(_063_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _255_ (
    .A(_080_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _256_ (
    .A(_040_),
    .B(_083_),
    .Y(_004_)
  );
  NOR _257_ (
    .A(_010_),
    .B(_049_),
    .Y(_084_)
  );
  NOT _258_ (
    .A(_084_),
    .Y(_085_)
  );
  NOR _259_ (
    .A(_064_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _260_ (
    .A(_039_),
    .B(_041_),
    .Y(_087_)
  );
  NAND _261_ (
    .A(_055_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _262_ (
    .A(_010_),
    .B(_009_),
    .Y(_089_)
  );
  NAND _263_ (
    .A(_008_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _264_ (
    .A(_056_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _265_ (
    .A(_080_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _266_ (
    .A(_088_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _267_ (
    .A(_066_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _268_ (
    .A(_043_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _269_ (
    .A(_086_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _270_ (
    .A(_040_),
    .B(_096_),
    .Y(_003_)
  );
  NOR _271_ (
    .A(_015_),
    .B(_091_),
    .Y(_097_)
  );
  NAND _272_ (
    .A(_063_),
    .B(_085_),
    .Y(_098_)
  );
  NAND _273_ (
    .A(_109_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _274_ (
    .A(_097_),
    .B(_099_),
    .Y(_002_)
  );
  NOR _275_ (
    .A(_041_),
    .B(_012_),
    .Y(_100_)
  );
  NOR _276_ (
    .A(_042_),
    .B(_011_),
    .Y(_101_)
  );
  NOR _277_ (
    .A(_100_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _278_ (
    .A(_039_),
    .B(_013_),
    .Y(_103_)
  );
  NAND _279_ (
    .A(_041_),
    .B(_012_),
    .Y(_104_)
  );
  NAND _280_ (
    .A(_103_),
    .B(_104_),
    .Y(_105_)
  );
  NOR _281_ (
    .A(_102_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _282_ (
    .A(_010_),
    .B(_048_),
    .Y(_107_)
  );
  NAND _283_ (
    .A(_109_),
    .B(_107_),
    .Y(_108_)
  );
  NOR _284_ (
    .A(_106_),
    .B(_108_),
    .Y(_000_)
  );
  NAND _285_ (
    .A(_041_),
    .B(_020_),
    .Y(_022_)
  );
  NAND _286_ (
    .A(_042_),
    .B(_019_),
    .Y(_023_)
  );
  NAND _287_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  NOR _288_ (
    .A(_039_),
    .B(_021_),
    .Y(_025_)
  );
  NOR _289_ (
    .A(_041_),
    .B(_020_),
    .Y(_026_)
  );
  NOR _290_ (
    .A(_025_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _291_ (
    .A(_024_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _292_ (
    .A(_010_),
    .B(_047_),
    .Y(_029_)
  );
  NAND _293_ (
    .A(_109_),
    .B(_028_),
    .Y(_030_)
  );
  NOR _294_ (
    .A(_029_),
    .B(_030_),
    .Y(_001_)
  );
  NAND _295_ (
    .A(_010_),
    .B(_050_),
    .Y(_031_)
  );
  NOT _296_ (
    .A(_031_),
    .Y(_032_)
  );
  NAND _297_ (
    .A(_010_),
    .B(_069_),
    .Y(_033_)
  );
  NOR _298_ (
    .A(_010_),
    .B(_050_),
    .Y(_034_)
  );
  NOR _299_ (
    .A(_032_),
    .B(_034_),
    .Y(_035_)
  );
  NAND _300_ (
    .A(_059_),
    .B(_035_),
    .Y(_036_)
  );
  NAND _301_ (
    .A(_033_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _302_ (
    .A(_086_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _303_ (
    .A(_040_),
    .B(_038_),
    .Y(_007_)
  );
  (* src = "control_logic_synth.v:48.1-88.4" *)
  DFF _304_ (
    .C(clk),
    .D(_127_),
    .Q(fifo_empty_synth)
  );
  (* src = "control_logic_synth.v:48.1-88.4" *)
  DFF _305_ (
    .C(clk),
    .D(_129_),
    .Q(fifo_full_synth)
  );
  (* src = "control_logic_synth.v:48.1-88.4" *)
  DFF _306_ (
    .C(clk),
    .D(_131_),
    .Q(error_synth)
  );
  (* src = "control_logic_synth.v:48.1-88.4" *)
  DFF _307_ (
    .C(clk),
    .D(_133_),
    .Q(counter[0])
  );
  (* src = "control_logic_synth.v:48.1-88.4" *)
  DFF _308_ (
    .C(clk),
    .D(_135_),
    .Q(counter[1])
  );
  (* src = "control_logic_synth.v:48.1-88.4" *)
  DFF _309_ (
    .C(clk),
    .D(_137_),
    .Q(counter[2])
  );
  assign _141_[1] = _115_;
  assign _148_[15:1] = { 14'h3fff, counter[2] };
  assign _149_[7:1] = 7'h7f;
  assign _150_[2:1] = { _125_, _122_ };
  assign _151_[0] = _123_;
  assign { _152_[3], _152_[1:0] } = { 1'h1, _122_, _150_[0] };
  assign _153_[1:0] = { _151_[1], _123_ };
  assign { _184_[31:3], _184_[0] } = { 29'h00000000, counter[0] };
  assign _185_[31:1] = { 29'h00000000, counter[2:1] };
  assign { _186_[31:3], _186_[0] } = { 28'h0000000, _184_[2], _185_[0] };
  assign { _195_[31:3], _195_[0] } = { 29'h1fffffff, _185_[0] };
  assign { _202_[30:2], _202_[0] } = { _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], _202_[31], counter[0] };
  assign { _203_[30:3], _203_[0] } = { _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _203_[31], _185_[0] };
  assign { _204_[30:3], _204_[1:0] } = { _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _204_[31], _203_[1], _185_[0] };
  assign _010_ = counter[2];
  assign _109_ = reset_L;
  assign _135_ = _006_;
  assign _009_ = counter[1];
  assign _133_ = _005_;
  assign _008_ = counter[0];
  assign _131_ = _004_;
  assign _014_ = error_synth;
  assign _129_ = _003_;
  assign _016_ = fifo_full_synth;
  assign _127_ = _002_;
  assign _015_ = fifo_empty_synth;
  assign _017_ = fifo_rd;
  assign _018_ = fifo_wr;
  assign almost_empty_synth = _000_;
  assign almost_full_synth = _001_;
  assign _019_ = full_threshold[0];
  assign _020_ = full_threshold[1];
  assign _021_ = full_threshold[2];
  assign _011_ = empty_threshold[0];
  assign _012_ = empty_threshold[1];
  assign _013_ = empty_threshold[2];
  assign _137_ = _007_;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "fifo.v:1.1-85.10" *)
module fifo_synth(fifo_data_out_synth, error_synth, almost_empty_synth, almost_full_synth, fifo_full_synth, fifo_empty_synth, fifo_wr, fifo_rd, fifo_data_in, full_threshold, empty_threshold, clk, reset_L);
  (* src = "fifo.v:10.12-10.24" *)
  output almost_empty_synth;
  (* src = "fifo.v:11.12-11.23" *)
  output almost_full_synth;
  (* src = "fifo.v:19.11-19.14" *)
  input clk;
  (* src = "fifo.v:78.24-78.34" *)
  wire [5:0] data_in_MM;
  (* src = "fifo.v:24.22-24.33" *)
  wire [5:0] data_out_MM;
  (* src = "fifo.v:18.23-18.38" *)
  input [2:0] empty_threshold;
  (* src = "fifo.v:9.12-9.17" *)
  output error_synth;
  (* src = "fifo.v:16.27-16.39" *)
  input [5:0] fifo_data_in;
  (* src = "fifo.v:8.32-8.45" *)
  output [5:0] fifo_data_out_synth;
  (* src = "fifo.v:13.12-13.22" *)
  output fifo_empty_synth;
  (* src = "fifo.v:12.12-12.21" *)
  output fifo_full_synth;
  (* src = "fifo.v:15.11-15.18" *)
  input fifo_rd;
  (* src = "fifo.v:14.11-14.18" *)
  input fifo_wr;
  (* src = "fifo.v:17.23-17.37" *)
  input [2:0] full_threshold;
  (* src = "fifo.v:25.8-25.11" *)
  wire pop;
  (* src = "fifo.v:26.8-26.12" *)
  wire push;
  (* src = "fifo.v:27.18-27.24" *)
  wire [2:0] rd_ptr;
  (* src = "fifo.v:20.11-20.18" *)
  input reset_L;
  (* src = "fifo.v:28.18-28.24" *)
  wire [2:0] wr_ptr;
  (* module_not_derived = 32'd1 *)
  (* src = "fifo.v:51.15-64.26" *)
  control_logic_synth control_log (
    .almost_empty_synth(almost_empty_synth),
    .almost_full_synth(almost_full_synth),
    .clk(clk),
    .empty_threshold(empty_threshold),
    .error_synth(error_synth),
    .fifo_empty_synth(fifo_empty_synth),
    .fifo_full_synth(fifo_full_synth),
    .fifo_rd(fifo_rd),
    .fifo_wr(fifo_wr),
    .full_threshold(full_threshold),
    .reset_L(reset_L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "fifo.v:66.8-76.22" *)
  memory_synth memoria (
    .clk(clk),
    .data_in_MM(fifo_data_in),
    .data_out_MM(data_out_MM),
    .pop(pop),
    .push(push),
    .rd_ptr(rd_ptr),
    .reset_L(reset_L),
    .wr_ptr(wr_ptr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "fifo.v:41.12-49.27" *)
  read_logic_synth read_log (
    .clk(clk),
    .fifo_empty_synth(fifo_empty_synth),
    .fifo_rd(fifo_rd),
    .pop(pop),
    .rd_ptr(rd_ptr),
    .reset_L(reset_L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "fifo.v:31.13-39.29" *)
  write_logic_synth write_log (
    .clk(clk),
    .fifo_full_synth(fifo_full_synth),
    .fifo_wr(fifo_wr),
    .push(push),
    .reset_L(reset_L),
    .wr_ptr(wr_ptr)
  );
  assign data_in_MM = fifo_data_in;
  assign fifo_data_out_synth = data_out_MM;
endmodule

(* dynports =  1  *)
(* src = "memory_synth.v:1.1-43.10" *)
module memory_synth(rd_ptr, wr_ptr, data_in_MM, push, pop, reset_L, clk, data_out_MM);
  (* src = "memory_synth.v:19.1-41.4" *)
  wire [5:0] _000_;
  (* src = "memory_synth.v:19.1-41.4" *)
  (* unused_bits = "2" *)
  wire [2:0] _001_;
  (* src = "memory_synth.v:19.1-41.4" *)
  wire [5:0] _002_;
  (* src = "memory_synth.v:19.1-41.4" *)
  wire [5:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _058_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _059_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _060_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _061_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _062_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  (* src = "memory_synth.v:11.11-11.14" *)
  wire _203_;
  (* src = "memory_synth.v:10.11-10.15" *)
  wire _204_;
  (* src = "memory_synth.v:7.23-7.29" *)
  wire _205_;
  (* src = "memory_synth.v:7.23-7.29" *)
  wire _206_;
  (* src = "memory_synth.v:12.11-12.18" *)
  wire _207_;
  (* src = "memory_synth.v:8.23-8.29" *)
  wire _208_;
  (* src = "memory_synth.v:8.23-8.29" *)
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire [5:0] _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire [1:0] _254_;
  wire [1:0] _255_;
  wire [1:0] _256_;
  wire [5:0] _257_;
  wire [5:0] _258_;
  wire _259_;
  wire [5:0] _260_;
  wire [5:0] _261_;
  wire [5:0] _262_;
  wire [5:0] _263_;
  (* src = "memory_synth.v:34.28-34.31" *)
  wire [5:0] _264_;
  wire [5:0] _265_;
  (* unused_bits = "2" *)
  wire [2:0] _266_;
  wire [5:0] \Mem[0] ;
  wire [5:0] \Mem[1] ;
  wire [5:0] \Mem[2] ;
  wire [5:0] \Mem[3] ;
  (* src = "memory_synth.v:13.11-13.14" *)
  input clk;
  (* src = "memory_synth.v:9.27-9.37" *)
  input [5:0] data_in_MM;
  (* src = "memory_synth.v:14.32-14.43" *)
  output [5:0] data_out_MM;
  (* src = "memory_synth.v:17.9-17.10" *)
  wire [31:0] i;
  (* src = "memory_synth.v:11.11-11.14" *)
  input pop;
  (* src = "memory_synth.v:10.11-10.15" *)
  input push;
  (* src = "memory_synth.v:7.23-7.29" *)
  input [2:0] rd_ptr;
  (* src = "memory_synth.v:12.11-12.18" *)
  input reset_L;
  (* src = "memory_synth.v:8.23-8.29" *)
  input [2:0] wr_ptr;
  NOT _267_ (
    .A(_009_),
    .Y(_172_)
  );
  NOT _268_ (
    .A(_008_),
    .Y(_173_)
  );
  NOT _269_ (
    .A(_007_),
    .Y(_174_)
  );
  NOT _270_ (
    .A(_006_),
    .Y(_175_)
  );
  NOT _271_ (
    .A(_005_),
    .Y(_176_)
  );
  NOT _272_ (
    .A(_004_),
    .Y(_177_)
  );
  NOT _273_ (
    .A(_027_),
    .Y(_178_)
  );
  NOT _274_ (
    .A(_026_),
    .Y(_179_)
  );
  NOT _275_ (
    .A(_025_),
    .Y(_180_)
  );
  NOT _276_ (
    .A(_024_),
    .Y(_181_)
  );
  NOT _277_ (
    .A(_023_),
    .Y(_182_)
  );
  NOT _278_ (
    .A(_022_),
    .Y(_183_)
  );
  NOT _279_ (
    .A(_207_),
    .Y(_184_)
  );
  NOT _280_ (
    .A(_204_),
    .Y(_185_)
  );
  NOT _281_ (
    .A(_208_),
    .Y(_186_)
  );
  NOT _282_ (
    .A(_209_),
    .Y(_187_)
  );
  NAND _283_ (
    .A(_207_),
    .B(_203_),
    .Y(_188_)
  );
  NOR _284_ (
    .A(_020_),
    .B(_205_),
    .Y(_189_)
  );
  NAND _285_ (
    .A(_179_),
    .B(_205_),
    .Y(_190_)
  );
  NAND _286_ (
    .A(_206_),
    .B(_190_),
    .Y(_191_)
  );
  NOR _287_ (
    .A(_189_),
    .B(_191_),
    .Y(_192_)
  );
  NAND _288_ (
    .A(_014_),
    .B(_205_),
    .Y(_193_)
  );
  NOT _289_ (
    .A(_193_),
    .Y(_194_)
  );
  NOR _290_ (
    .A(_173_),
    .B(_205_),
    .Y(_195_)
  );
  NOR _291_ (
    .A(_194_),
    .B(_195_),
    .Y(_196_)
  );
  NOR _292_ (
    .A(_206_),
    .B(_196_),
    .Y(_197_)
  );
  NOR _293_ (
    .A(_192_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _294_ (
    .A(_188_),
    .B(_198_),
    .Y(_056_)
  );
  NOR _295_ (
    .A(_019_),
    .B(_205_),
    .Y(_199_)
  );
  NAND _296_ (
    .A(_180_),
    .B(_205_),
    .Y(_200_)
  );
  NAND _297_ (
    .A(_206_),
    .B(_200_),
    .Y(_201_)
  );
  NOR _298_ (
    .A(_199_),
    .B(_201_),
    .Y(_202_)
  );
  NAND _299_ (
    .A(_013_),
    .B(_205_),
    .Y(_064_)
  );
  NOT _300_ (
    .A(_064_),
    .Y(_065_)
  );
  NOR _301_ (
    .A(_174_),
    .B(_205_),
    .Y(_066_)
  );
  NOR _302_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _303_ (
    .A(_206_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _304_ (
    .A(_202_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _305_ (
    .A(_188_),
    .B(_069_),
    .Y(_055_)
  );
  NOR _306_ (
    .A(_018_),
    .B(_205_),
    .Y(_070_)
  );
  NAND _307_ (
    .A(_181_),
    .B(_205_),
    .Y(_071_)
  );
  NAND _308_ (
    .A(_206_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _309_ (
    .A(_070_),
    .B(_072_),
    .Y(_073_)
  );
  NAND _310_ (
    .A(_012_),
    .B(_205_),
    .Y(_074_)
  );
  NOT _311_ (
    .A(_074_),
    .Y(_075_)
  );
  NOR _312_ (
    .A(_175_),
    .B(_205_),
    .Y(_076_)
  );
  NOR _313_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _314_ (
    .A(_206_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _315_ (
    .A(_073_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _316_ (
    .A(_188_),
    .B(_079_),
    .Y(_054_)
  );
  NOR _317_ (
    .A(_017_),
    .B(_205_),
    .Y(_080_)
  );
  NAND _318_ (
    .A(_182_),
    .B(_205_),
    .Y(_081_)
  );
  NAND _319_ (
    .A(_206_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _320_ (
    .A(_080_),
    .B(_082_),
    .Y(_083_)
  );
  NAND _321_ (
    .A(_011_),
    .B(_205_),
    .Y(_084_)
  );
  NOT _322_ (
    .A(_084_),
    .Y(_085_)
  );
  NOR _323_ (
    .A(_176_),
    .B(_205_),
    .Y(_086_)
  );
  NOR _324_ (
    .A(_085_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _325_ (
    .A(_206_),
    .B(_087_),
    .Y(_088_)
  );
  NOR _326_ (
    .A(_083_),
    .B(_088_),
    .Y(_089_)
  );
  NOR _327_ (
    .A(_188_),
    .B(_089_),
    .Y(_053_)
  );
  NOR _328_ (
    .A(_016_),
    .B(_205_),
    .Y(_090_)
  );
  NAND _329_ (
    .A(_183_),
    .B(_205_),
    .Y(_091_)
  );
  NAND _330_ (
    .A(_206_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _331_ (
    .A(_090_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _332_ (
    .A(_010_),
    .B(_205_),
    .Y(_094_)
  );
  NOT _333_ (
    .A(_094_),
    .Y(_095_)
  );
  NOR _334_ (
    .A(_177_),
    .B(_205_),
    .Y(_096_)
  );
  NOR _335_ (
    .A(_095_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _336_ (
    .A(_206_),
    .B(_097_),
    .Y(_098_)
  );
  NOR _337_ (
    .A(_093_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _338_ (
    .A(_188_),
    .B(_099_),
    .Y(_052_)
  );
  NOR _339_ (
    .A(_184_),
    .B(_185_),
    .Y(_100_)
  );
  NAND _340_ (
    .A(_187_),
    .B(_100_),
    .Y(_101_)
  );
  NOR _341_ (
    .A(_208_),
    .B(_101_),
    .Y(_102_)
  );
  NOR _342_ (
    .A(_184_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _343_ (
    .A(_009_),
    .B(_103_),
    .Y(_104_)
  );
  NAND _344_ (
    .A(_063_),
    .B(_102_),
    .Y(_105_)
  );
  NAND _345_ (
    .A(_104_),
    .B(_105_),
    .Y(_051_)
  );
  NAND _346_ (
    .A(_008_),
    .B(_103_),
    .Y(_106_)
  );
  NAND _347_ (
    .A(_062_),
    .B(_102_),
    .Y(_107_)
  );
  NAND _348_ (
    .A(_106_),
    .B(_107_),
    .Y(_050_)
  );
  NAND _349_ (
    .A(_007_),
    .B(_103_),
    .Y(_108_)
  );
  NAND _350_ (
    .A(_061_),
    .B(_102_),
    .Y(_109_)
  );
  NAND _351_ (
    .A(_108_),
    .B(_109_),
    .Y(_049_)
  );
  NAND _352_ (
    .A(_006_),
    .B(_103_),
    .Y(_110_)
  );
  NAND _353_ (
    .A(_060_),
    .B(_102_),
    .Y(_111_)
  );
  NAND _354_ (
    .A(_110_),
    .B(_111_),
    .Y(_048_)
  );
  NAND _355_ (
    .A(_005_),
    .B(_103_),
    .Y(_112_)
  );
  NAND _356_ (
    .A(_059_),
    .B(_102_),
    .Y(_113_)
  );
  NAND _357_ (
    .A(_112_),
    .B(_113_),
    .Y(_047_)
  );
  NAND _358_ (
    .A(_004_),
    .B(_103_),
    .Y(_114_)
  );
  NAND _359_ (
    .A(_058_),
    .B(_102_),
    .Y(_115_)
  );
  NAND _360_ (
    .A(_114_),
    .B(_115_),
    .Y(_046_)
  );
  NOR _361_ (
    .A(_186_),
    .B(_101_),
    .Y(_116_)
  );
  NOR _362_ (
    .A(_184_),
    .B(_116_),
    .Y(_117_)
  );
  NAND _363_ (
    .A(_015_),
    .B(_117_),
    .Y(_118_)
  );
  NAND _364_ (
    .A(_063_),
    .B(_116_),
    .Y(_119_)
  );
  NAND _365_ (
    .A(_118_),
    .B(_119_),
    .Y(_045_)
  );
  NAND _366_ (
    .A(_014_),
    .B(_117_),
    .Y(_120_)
  );
  NAND _367_ (
    .A(_062_),
    .B(_116_),
    .Y(_121_)
  );
  NAND _368_ (
    .A(_120_),
    .B(_121_),
    .Y(_044_)
  );
  NAND _369_ (
    .A(_013_),
    .B(_117_),
    .Y(_122_)
  );
  NAND _370_ (
    .A(_061_),
    .B(_116_),
    .Y(_123_)
  );
  NAND _371_ (
    .A(_122_),
    .B(_123_),
    .Y(_043_)
  );
  NAND _372_ (
    .A(_012_),
    .B(_117_),
    .Y(_124_)
  );
  NAND _373_ (
    .A(_060_),
    .B(_116_),
    .Y(_125_)
  );
  NAND _374_ (
    .A(_124_),
    .B(_125_),
    .Y(_042_)
  );
  NAND _375_ (
    .A(_011_),
    .B(_117_),
    .Y(_126_)
  );
  NAND _376_ (
    .A(_059_),
    .B(_116_),
    .Y(_127_)
  );
  NAND _377_ (
    .A(_126_),
    .B(_127_),
    .Y(_041_)
  );
  NAND _378_ (
    .A(_010_),
    .B(_117_),
    .Y(_128_)
  );
  NAND _379_ (
    .A(_058_),
    .B(_116_),
    .Y(_129_)
  );
  NAND _380_ (
    .A(_128_),
    .B(_129_),
    .Y(_040_)
  );
  NOR _381_ (
    .A(_185_),
    .B(_187_),
    .Y(_130_)
  );
  NAND _382_ (
    .A(_204_),
    .B(_209_),
    .Y(_131_)
  );
  NAND _383_ (
    .A(_207_),
    .B(_130_),
    .Y(_132_)
  );
  NOR _384_ (
    .A(_208_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _385_ (
    .A(_184_),
    .B(_133_),
    .Y(_134_)
  );
  NAND _386_ (
    .A(_021_),
    .B(_134_),
    .Y(_135_)
  );
  NAND _387_ (
    .A(_063_),
    .B(_133_),
    .Y(_136_)
  );
  NAND _388_ (
    .A(_135_),
    .B(_136_),
    .Y(_039_)
  );
  NAND _389_ (
    .A(_020_),
    .B(_134_),
    .Y(_137_)
  );
  NAND _390_ (
    .A(_062_),
    .B(_133_),
    .Y(_138_)
  );
  NAND _391_ (
    .A(_137_),
    .B(_138_),
    .Y(_038_)
  );
  NAND _392_ (
    .A(_019_),
    .B(_134_),
    .Y(_139_)
  );
  NAND _393_ (
    .A(_061_),
    .B(_133_),
    .Y(_140_)
  );
  NAND _394_ (
    .A(_139_),
    .B(_140_),
    .Y(_037_)
  );
  NAND _395_ (
    .A(_018_),
    .B(_134_),
    .Y(_141_)
  );
  NAND _396_ (
    .A(_060_),
    .B(_133_),
    .Y(_142_)
  );
  NAND _397_ (
    .A(_141_),
    .B(_142_),
    .Y(_036_)
  );
  NAND _398_ (
    .A(_017_),
    .B(_134_),
    .Y(_143_)
  );
  NAND _399_ (
    .A(_059_),
    .B(_133_),
    .Y(_144_)
  );
  NAND _400_ (
    .A(_143_),
    .B(_144_),
    .Y(_035_)
  );
  NAND _401_ (
    .A(_016_),
    .B(_134_),
    .Y(_145_)
  );
  NAND _402_ (
    .A(_058_),
    .B(_133_),
    .Y(_146_)
  );
  NAND _403_ (
    .A(_145_),
    .B(_146_),
    .Y(_034_)
  );
  NOR _404_ (
    .A(_186_),
    .B(_131_),
    .Y(_147_)
  );
  NOR _405_ (
    .A(_184_),
    .B(_147_),
    .Y(_148_)
  );
  NAND _406_ (
    .A(_027_),
    .B(_148_),
    .Y(_149_)
  );
  NOR _407_ (
    .A(_186_),
    .B(_132_),
    .Y(_150_)
  );
  NAND _408_ (
    .A(_063_),
    .B(_150_),
    .Y(_151_)
  );
  NAND _409_ (
    .A(_149_),
    .B(_151_),
    .Y(_033_)
  );
  NAND _410_ (
    .A(_026_),
    .B(_148_),
    .Y(_152_)
  );
  NAND _411_ (
    .A(_062_),
    .B(_150_),
    .Y(_153_)
  );
  NAND _412_ (
    .A(_152_),
    .B(_153_),
    .Y(_032_)
  );
  NAND _413_ (
    .A(_025_),
    .B(_148_),
    .Y(_154_)
  );
  NAND _414_ (
    .A(_061_),
    .B(_150_),
    .Y(_155_)
  );
  NAND _415_ (
    .A(_154_),
    .B(_155_),
    .Y(_031_)
  );
  NAND _416_ (
    .A(_024_),
    .B(_148_),
    .Y(_156_)
  );
  NAND _417_ (
    .A(_060_),
    .B(_150_),
    .Y(_157_)
  );
  NAND _418_ (
    .A(_156_),
    .B(_157_),
    .Y(_030_)
  );
  NAND _419_ (
    .A(_023_),
    .B(_148_),
    .Y(_158_)
  );
  NAND _420_ (
    .A(_059_),
    .B(_150_),
    .Y(_159_)
  );
  NAND _421_ (
    .A(_158_),
    .B(_159_),
    .Y(_029_)
  );
  NAND _422_ (
    .A(_022_),
    .B(_148_),
    .Y(_160_)
  );
  NAND _423_ (
    .A(_058_),
    .B(_150_),
    .Y(_161_)
  );
  NAND _424_ (
    .A(_160_),
    .B(_161_),
    .Y(_028_)
  );
  NOR _425_ (
    .A(_021_),
    .B(_205_),
    .Y(_162_)
  );
  NAND _426_ (
    .A(_178_),
    .B(_205_),
    .Y(_163_)
  );
  NAND _427_ (
    .A(_206_),
    .B(_163_),
    .Y(_164_)
  );
  NOR _428_ (
    .A(_162_),
    .B(_164_),
    .Y(_165_)
  );
  NAND _429_ (
    .A(_015_),
    .B(_205_),
    .Y(_166_)
  );
  NOT _430_ (
    .A(_166_),
    .Y(_167_)
  );
  NOR _431_ (
    .A(_172_),
    .B(_205_),
    .Y(_168_)
  );
  NOR _432_ (
    .A(_167_),
    .B(_168_),
    .Y(_169_)
  );
  NOR _433_ (
    .A(_206_),
    .B(_169_),
    .Y(_170_)
  );
  NOR _434_ (
    .A(_165_),
    .B(_170_),
    .Y(_171_)
  );
  NOR _435_ (
    .A(_188_),
    .B(_171_),
    .Y(_057_)
  );
  DFF _436_ (
    .C(clk),
    .D(_224_),
    .Q(\Mem[3] [0])
  );
  DFF _437_ (
    .C(clk),
    .D(_225_),
    .Q(\Mem[3] [1])
  );
  DFF _438_ (
    .C(clk),
    .D(_226_),
    .Q(\Mem[3] [2])
  );
  DFF _439_ (
    .C(clk),
    .D(_227_),
    .Q(\Mem[3] [3])
  );
  DFF _440_ (
    .C(clk),
    .D(_228_),
    .Q(\Mem[3] [4])
  );
  DFF _441_ (
    .C(clk),
    .D(_229_),
    .Q(\Mem[3] [5])
  );
  DFF _442_ (
    .C(clk),
    .D(_230_),
    .Q(\Mem[2] [0])
  );
  DFF _443_ (
    .C(clk),
    .D(_231_),
    .Q(\Mem[2] [1])
  );
  DFF _444_ (
    .C(clk),
    .D(_232_),
    .Q(\Mem[2] [2])
  );
  DFF _445_ (
    .C(clk),
    .D(_233_),
    .Q(\Mem[2] [3])
  );
  DFF _446_ (
    .C(clk),
    .D(_234_),
    .Q(\Mem[2] [4])
  );
  DFF _447_ (
    .C(clk),
    .D(_235_),
    .Q(\Mem[2] [5])
  );
  DFF _448_ (
    .C(clk),
    .D(_236_),
    .Q(\Mem[1] [0])
  );
  DFF _449_ (
    .C(clk),
    .D(_237_),
    .Q(\Mem[1] [1])
  );
  DFF _450_ (
    .C(clk),
    .D(_238_),
    .Q(\Mem[1] [2])
  );
  DFF _451_ (
    .C(clk),
    .D(_239_),
    .Q(\Mem[1] [3])
  );
  DFF _452_ (
    .C(clk),
    .D(_240_),
    .Q(\Mem[1] [4])
  );
  DFF _453_ (
    .C(clk),
    .D(_241_),
    .Q(\Mem[1] [5])
  );
  DFF _454_ (
    .C(clk),
    .D(_242_),
    .Q(\Mem[0] [0])
  );
  DFF _455_ (
    .C(clk),
    .D(_243_),
    .Q(\Mem[0] [1])
  );
  DFF _456_ (
    .C(clk),
    .D(_244_),
    .Q(\Mem[0] [2])
  );
  DFF _457_ (
    .C(clk),
    .D(_245_),
    .Q(\Mem[0] [3])
  );
  DFF _458_ (
    .C(clk),
    .D(_246_),
    .Q(\Mem[0] [4])
  );
  DFF _459_ (
    .C(clk),
    .D(_247_),
    .Q(\Mem[0] [5])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _460_ (
    .C(clk),
    .D(_248_),
    .Q(data_out_MM[0])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _461_ (
    .C(clk),
    .D(_249_),
    .Q(data_out_MM[1])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _462_ (
    .C(clk),
    .D(_250_),
    .Q(data_out_MM[2])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _463_ (
    .C(clk),
    .D(_251_),
    .Q(data_out_MM[3])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _464_ (
    .C(clk),
    .D(_252_),
    .Q(data_out_MM[4])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _465_ (
    .C(clk),
    .D(_253_),
    .Q(data_out_MM[5])
  );
  assign _000_[4:0] = { _000_[5], _000_[5], _000_[5], _000_[5], _000_[5] };
  assign _003_[4:0] = { _003_[5], _003_[5], _003_[5], _003_[5], _003_[5] };
  assign _254_[0] = _000_[5];
  assign _255_[0] = _000_[5];
  assign _256_[0] = _000_[5];
  assign _260_[4:0] = { _260_[5], _260_[5], _260_[5], _260_[5], _260_[5] };
  assign i = 32'd4;
  assign _252_ = _056_;
  assign _251_ = _055_;
  assign _250_ = _054_;
  assign _249_ = _053_;
  assign _248_ = _052_;
  assign _009_ = \Mem[0] [5];
  assign _247_ = _051_;
  assign _008_ = \Mem[0] [4];
  assign _246_ = _050_;
  assign _007_ = \Mem[0] [3];
  assign _245_ = _049_;
  assign _006_ = \Mem[0] [2];
  assign _244_ = _048_;
  assign _005_ = \Mem[0] [1];
  assign _243_ = _047_;
  assign _004_ = \Mem[0] [0];
  assign _242_ = _046_;
  assign _015_ = \Mem[1] [5];
  assign _241_ = _045_;
  assign _014_ = \Mem[1] [4];
  assign _240_ = _044_;
  assign _013_ = \Mem[1] [3];
  assign _239_ = _043_;
  assign _012_ = \Mem[1] [2];
  assign _238_ = _042_;
  assign _011_ = \Mem[1] [1];
  assign _237_ = _041_;
  assign _010_ = \Mem[1] [0];
  assign _236_ = _040_;
  assign _021_ = \Mem[2] [5];
  assign _235_ = _039_;
  assign _020_ = \Mem[2] [4];
  assign _234_ = _038_;
  assign _019_ = \Mem[2] [3];
  assign _233_ = _037_;
  assign _018_ = \Mem[2] [2];
  assign _232_ = _036_;
  assign _017_ = \Mem[2] [1];
  assign _231_ = _035_;
  assign _016_ = \Mem[2] [0];
  assign _230_ = _034_;
  assign _027_ = \Mem[3] [5];
  assign _229_ = _033_;
  assign _026_ = \Mem[3] [4];
  assign _228_ = _032_;
  assign _025_ = \Mem[3] [3];
  assign _227_ = _031_;
  assign _024_ = \Mem[3] [2];
  assign _226_ = _030_;
  assign _023_ = \Mem[3] [1];
  assign _225_ = _029_;
  assign _022_ = \Mem[3] [0];
  assign _224_ = _028_;
  assign _207_ = reset_L;
  assign _203_ = pop;
  assign _206_ = rd_ptr[1];
  assign _204_ = push;
  assign _058_ = data_in_MM[0];
  assign _059_ = data_in_MM[1];
  assign _060_ = data_in_MM[2];
  assign _061_ = data_in_MM[3];
  assign _062_ = data_in_MM[4];
  assign _063_ = data_in_MM[5];
  assign _205_ = rd_ptr[0];
  assign _208_ = wr_ptr[0];
  assign _209_ = wr_ptr[1];
  assign _253_ = _057_;
endmodule

(* dynports =  1  *)
(* src = "read_logic_synth.v:1.1-50.10" *)
module read_logic_synth(fifo_rd, fifo_empty_synth, clk, reset_L, rd_ptr, pop);
  (* src = "read_logic_synth.v:16.1-29.4" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "read_logic_synth.v:9.11-9.21" *)
  wire _04_;
  (* src = "read_logic_synth.v:8.11-8.18" *)
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "read_logic_synth.v:13.16-13.19" *)
  wire _17_;
  (* src = "read_logic_synth.v:12.28-12.34" *)
  wire _18_;
  (* src = "read_logic_synth.v:12.28-12.34" *)
  wire _19_;
  (* src = "read_logic_synth.v:12.28-12.34" *)
  wire _20_;
  (* src = "read_logic_synth.v:11.11-11.18" *)
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  (* src = "read_logic_synth.v:18.24-18.35" *)
  wire _31_;
  wire [2:0] _32_;
  (* force_downto = 32'd1 *)
  (* src = "read_logic_synth.v:39.23-39.33|write_logic_synth.v:38.23-38.33|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _33_;
  (* force_downto = 32'd1 *)
  (* src = "read_logic_synth.v:39.23-39.33|write_logic_synth.v:38.23-38.33|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _34_;
  (* force_downto = 32'd1 *)
  (* src = "read_logic_synth.v:39.23-39.33|write_logic_synth.v:38.23-38.33|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [31:0] _35_;
  (* src = "read_logic_synth.v:10.11-10.14" *)
  input clk;
  (* src = "read_logic_synth.v:9.11-9.21" *)
  input fifo_empty_synth;
  (* src = "read_logic_synth.v:8.11-8.18" *)
  input fifo_rd;
  (* src = "read_logic_synth.v:13.16-13.19" *)
  output pop;
  (* src = "read_logic_synth.v:12.28-12.34" *)
  output [2:0] rd_ptr;
  (* src = "read_logic_synth.v:11.11-11.18" *)
  input reset_L;
  NOT _36_ (
    .A(_20_),
    .Y(_06_)
  );
  NOT _37_ (
    .A(_21_),
    .Y(_07_)
  );
  NOT _38_ (
    .A(_18_),
    .Y(_08_)
  );
  NOT _39_ (
    .A(_04_),
    .Y(_09_)
  );
  NAND _40_ (
    .A(_09_),
    .B(_05_),
    .Y(_10_)
  );
  NOR _41_ (
    .A(_08_),
    .B(_10_),
    .Y(_11_)
  );
  NOR _42_ (
    .A(_19_),
    .B(_11_),
    .Y(_12_)
  );
  NAND _43_ (
    .A(_19_),
    .B(_11_),
    .Y(_13_)
  );
  NAND _44_ (
    .A(_21_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _45_ (
    .A(_12_),
    .B(_14_),
    .Y(_02_)
  );
  NAND _46_ (
    .A(_08_),
    .B(_10_),
    .Y(_15_)
  );
  NAND _47_ (
    .A(_21_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _48_ (
    .A(_11_),
    .B(_16_),
    .Y(_01_)
  );
  NOR _49_ (
    .A(_07_),
    .B(_10_),
    .Y(_17_)
  );
  NOR _50_ (
    .A(_06_),
    .B(_14_),
    .Y(_03_)
  );
  (* src = "read_logic_synth.v:31.1-48.4" *)
  DFF _51_ (
    .C(clk),
    .D(_24_),
    .Q(rd_ptr[0])
  );
  (* src = "read_logic_synth.v:31.1-48.4" *)
  DFF _52_ (
    .C(clk),
    .D(_26_),
    .Q(rd_ptr[1])
  );
  (* src = "read_logic_synth.v:31.1-48.4" *)
  DFF _53_ (
    .C(clk),
    .D(_28_),
    .Q(rd_ptr[2])
  );
  assign { _33_[31:3], _33_[0] } = { 29'h00000000, rd_ptr[0] };
  assign _34_[31:1] = { 29'h00000000, rd_ptr[2:1] };
  assign { _35_[31:3], _35_[0] } = { 28'h0000000, _33_[2], _34_[0] };
  assign _20_ = rd_ptr[2];
  assign _21_ = reset_L;
  assign _26_ = _02_;
  assign _19_ = rd_ptr[1];
  assign _24_ = _01_;
  assign _18_ = rd_ptr[0];
  assign _04_ = fifo_empty_synth;
  assign _05_ = fifo_rd;
  assign pop = _17_;
  assign _28_ = _03_;
endmodule

(* dynports =  1  *)
(* src = "write_logic_synth.v:1.1-51.10" *)
module write_logic_synth(fifo_wr, fifo_full_synth, clk, reset_L, wr_ptr, push);
  (* src = "write_logic_synth.v:16.1-28.4" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "write_logic_synth.v:9.11-9.20" *)
  wire _04_;
  (* src = "write_logic_synth.v:8.11-8.18" *)
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  (* src = "write_logic_synth.v:13.16-13.20" *)
  wire _17_;
  (* src = "write_logic_synth.v:11.11-11.18" *)
  wire _18_;
  (* src = "write_logic_synth.v:12.28-12.34" *)
  wire _19_;
  (* src = "write_logic_synth.v:12.28-12.34" *)
  wire _20_;
  (* src = "write_logic_synth.v:12.28-12.34" *)
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  (* src = "write_logic_synth.v:18.24-18.34" *)
  wire _31_;
  wire [2:0] _32_;
  (* force_downto = 32'd1 *)
  (* src = "write_logic_synth.v:38.23-38.33|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _33_;
  (* force_downto = 32'd1 *)
  (* src = "write_logic_synth.v:38.23-38.33|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _34_;
  (* force_downto = 32'd1 *)
  (* src = "write_logic_synth.v:38.23-38.33|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [31:0] _35_;
  (* src = "write_logic_synth.v:10.11-10.14" *)
  input clk;
  (* src = "write_logic_synth.v:9.11-9.20" *)
  input fifo_full_synth;
  (* src = "write_logic_synth.v:8.11-8.18" *)
  input fifo_wr;
  (* src = "write_logic_synth.v:13.16-13.20" *)
  output push;
  (* src = "write_logic_synth.v:11.11-11.18" *)
  input reset_L;
  (* src = "write_logic_synth.v:12.28-12.34" *)
  output [2:0] wr_ptr;
  NOT _36_ (
    .A(_21_),
    .Y(_06_)
  );
  NOT _37_ (
    .A(_18_),
    .Y(_07_)
  );
  NOT _38_ (
    .A(_19_),
    .Y(_08_)
  );
  NOT _39_ (
    .A(_04_),
    .Y(_09_)
  );
  NAND _40_ (
    .A(_09_),
    .B(_05_),
    .Y(_10_)
  );
  NOR _41_ (
    .A(_08_),
    .B(_10_),
    .Y(_11_)
  );
  NOR _42_ (
    .A(_20_),
    .B(_11_),
    .Y(_12_)
  );
  NAND _43_ (
    .A(_20_),
    .B(_11_),
    .Y(_13_)
  );
  NAND _44_ (
    .A(_18_),
    .B(_13_),
    .Y(_14_)
  );
  NOR _45_ (
    .A(_12_),
    .B(_14_),
    .Y(_02_)
  );
  NAND _46_ (
    .A(_08_),
    .B(_10_),
    .Y(_15_)
  );
  NAND _47_ (
    .A(_18_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _48_ (
    .A(_11_),
    .B(_16_),
    .Y(_01_)
  );
  NOR _49_ (
    .A(_07_),
    .B(_10_),
    .Y(_17_)
  );
  NOR _50_ (
    .A(_06_),
    .B(_14_),
    .Y(_03_)
  );
  (* src = "write_logic_synth.v:30.1-47.4" *)
  DFF _51_ (
    .C(clk),
    .D(_24_),
    .Q(wr_ptr[0])
  );
  (* src = "write_logic_synth.v:30.1-47.4" *)
  DFF _52_ (
    .C(clk),
    .D(_26_),
    .Q(wr_ptr[1])
  );
  (* src = "write_logic_synth.v:30.1-47.4" *)
  DFF _53_ (
    .C(clk),
    .D(_28_),
    .Q(wr_ptr[2])
  );
  assign { _33_[31:3], _33_[0] } = { 29'h00000000, wr_ptr[0] };
  assign _34_[31:1] = { 29'h00000000, wr_ptr[2:1] };
  assign { _35_[31:3], _35_[0] } = { 28'h0000000, _33_[2], _34_[0] };
  assign _21_ = wr_ptr[2];
  assign _18_ = reset_L;
  assign _26_ = _02_;
  assign _20_ = wr_ptr[1];
  assign _24_ = _01_;
  assign _19_ = wr_ptr[0];
  assign _04_ = fifo_full_synth;
  assign _05_ = fifo_wr;
  assign push = _17_;
  assign _28_ = _03_;
endmodule
