/* Generated by Yosys 0.9+3565 (git sha1 474cd02e, gcc 9.3.0-10ubuntu2 -fPIC -Os) */

(* dynports =  1  *)
(* hdlname = "\\control_logic_synth" *)
(* src = "control_logic_synth.v:1.1-98.10" *)
module \$paramod\control_logic_synth\MEM_SIZE=4 (full_threshold, empty_threshold, fifo_rd, fifo_wr, clk, reset_L, error_synth, almost_empty_synth, almost_full_synth, fifo_full_synth, fifo_empty_synth);
  (* src = "control_logic_synth.v:75.1-96.4" *)
  wire _000_;
  (* src = "control_logic_synth.v:75.1-96.4" *)
  wire _001_;
  (* src = "control_logic_synth.v:15.16-15.28" *)
  wire _002_;
  (* src = "control_logic_synth.v:16.16-16.27" *)
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire _008_;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire _009_;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire _010_;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  wire _011_;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  wire _012_;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  wire _013_;
  (* src = "control_logic_synth.v:14.16-14.21" *)
  wire _014_;
  (* src = "control_logic_synth.v:18.16-18.26" *)
  wire _015_;
  (* src = "control_logic_synth.v:17.16-17.25" *)
  wire _016_;
  (* src = "control_logic_synth.v:10.11-10.18" *)
  wire _017_;
  (* src = "control_logic_synth.v:11.11-11.18" *)
  wire _018_;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  wire _019_;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  wire _020_;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  (* src = "control_logic_synth.v:13.11-13.18" *)
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire [15:0] _102_;
  wire [7:0] _103_;
  (* src = "control_logic_synth.v:26.13-26.38" *)
  wire _104_;
  (* src = "control_logic_synth.v:34.13-34.39" *)
  wire _105_;
  (* src = "control_logic_synth.v:60.14-60.33" *)
  wire _106_;
  (* src = "control_logic_synth.v:60.14-60.46" *)
  wire _107_;
  (* src = "control_logic_synth.v:60.52-60.71" *)
  wire _108_;
  (* src = "control_logic_synth.v:60.52-60.85" *)
  wire _109_;
  (* src = "control_logic_synth.v:63.18-63.52" *)
  wire _110_;
  (* src = "control_logic_synth.v:67.18-67.51" *)
  wire _111_;
  (* src = "control_logic_synth.v:60.13-60.86" *)
  wire _112_;
  (* src = "control_logic_synth.v:60.25-60.33" *)
  wire _113_;
  (* src = "control_logic_synth.v:60.63-60.71" *)
  wire _114_;
  (* src = "control_logic_synth.v:63.41-63.52" *)
  wire _115_;
  (* src = "control_logic_synth.v:67.41-67.51" *)
  wire _116_;
  wire [2:0] _117_;
  wire [2:0] _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:68.24-68.35|write_logic_synth.v:39.23-39.33|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _122_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:68.24-68.35|write_logic_synth.v:39.23-39.33|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _123_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:68.24-68.35|write_logic_synth.v:39.23-39.33|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [31:0] _124_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [2:0] _125_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [2:0] _126_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _127_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [2:0] _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:77.13-77.32|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _133_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:77.13-77.32|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _134_;
  wire _135_;
  wire _136_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [2:0] _137_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [2:0] _138_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [2:0] _139_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:214.23-214.24" *)
  wire [2:0] _140_;
  wire _141_;
  wire _142_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:64.24-64.35|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _143_;
  (* force_downto = 32'd1 *)
  (* src = "control_logic_synth.v:64.24-64.35|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _144_;
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _145_;
  (* src = "control_logic_synth.v:26.13-26.38|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _146_;
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _147_;
  (* src = "control_logic_synth.v:34.13-34.39|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _148_;
  (* src = "control_logic_synth.v:64.24-64.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _149_;
  (* src = "control_logic_synth.v:15.16-15.28" *)
  output almost_empty_synth;
  (* src = "control_logic_synth.v:16.16-16.27" *)
  output almost_full_synth;
  (* src = "control_logic_synth.v:12.11-12.14" *)
  input clk;
  (* src = "control_logic_synth.v:20.17-20.24" *)
  wire [2:0] counter;
  (* src = "control_logic_synth.v:9.23-9.38" *)
  input [2:0] empty_threshold;
  (* src = "control_logic_synth.v:14.16-14.21" *)
  output error_synth;
  (* src = "control_logic_synth.v:18.16-18.26" *)
  output fifo_empty_synth;
  (* src = "control_logic_synth.v:17.16-17.25" *)
  output fifo_full_synth;
  (* src = "control_logic_synth.v:10.11-10.18" *)
  input fifo_rd;
  (* src = "control_logic_synth.v:11.11-11.18" *)
  input fifo_wr;
  (* src = "control_logic_synth.v:8.23-8.37" *)
  input [2:0] full_threshold;
  (* src = "control_logic_synth.v:13.11-13.18" *)
  input reset_L;
  NOT _150_ (
    .A(_086_),
    .Y(_022_)
  );
  NOT _151_ (
    .A(_010_),
    .Y(_023_)
  );
  NOT _152_ (
    .A(_009_),
    .Y(_024_)
  );
  NOT _153_ (
    .A(_008_),
    .Y(_025_)
  );
  NOT _154_ (
    .A(_017_),
    .Y(_026_)
  );
  NOT _155_ (
    .A(_018_),
    .Y(_027_)
  );
  NOT _156_ (
    .A(_020_),
    .Y(_028_)
  );
  NOT _157_ (
    .A(_013_),
    .Y(_029_)
  );
  NOR _158_ (
    .A(_026_),
    .B(_018_),
    .Y(_030_)
  );
  NOT _159_ (
    .A(_030_),
    .Y(_031_)
  );
  NOR _160_ (
    .A(_023_),
    .B(_030_),
    .Y(_032_)
  );
  NOR _161_ (
    .A(_009_),
    .B(_008_),
    .Y(_033_)
  );
  NOT _162_ (
    .A(_033_),
    .Y(_034_)
  );
  NAND _163_ (
    .A(_023_),
    .B(_033_),
    .Y(_035_)
  );
  NOR _164_ (
    .A(_022_),
    .B(_035_),
    .Y(_015_)
  );
  NOT _165_ (
    .A(_015_),
    .Y(_036_)
  );
  NOR _166_ (
    .A(_031_),
    .B(_015_),
    .Y(_037_)
  );
  NAND _167_ (
    .A(_030_),
    .B(_036_),
    .Y(_038_)
  );
  NAND _168_ (
    .A(_010_),
    .B(_034_),
    .Y(_039_)
  );
  NAND _169_ (
    .A(_035_),
    .B(_039_),
    .Y(_040_)
  );
  NAND _170_ (
    .A(_037_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _171_ (
    .A(_017_),
    .B(_027_),
    .Y(_042_)
  );
  NAND _172_ (
    .A(_026_),
    .B(_018_),
    .Y(_043_)
  );
  NOR _173_ (
    .A(_022_),
    .B(_023_),
    .Y(_016_)
  );
  NOR _174_ (
    .A(_043_),
    .B(_016_),
    .Y(_044_)
  );
  NOT _175_ (
    .A(_044_),
    .Y(_045_)
  );
  NAND _176_ (
    .A(_009_),
    .B(_008_),
    .Y(_046_)
  );
  NOT _177_ (
    .A(_046_),
    .Y(_047_)
  );
  NOR _178_ (
    .A(_010_),
    .B(_046_),
    .Y(_048_)
  );
  NAND _179_ (
    .A(_044_),
    .B(_048_),
    .Y(_049_)
  );
  NAND _180_ (
    .A(_041_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _181_ (
    .A(_032_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _182_ (
    .A(_037_),
    .B(_044_),
    .Y(_052_)
  );
  NAND _183_ (
    .A(_038_),
    .B(_045_),
    .Y(_053_)
  );
  NOR _184_ (
    .A(_022_),
    .B(_051_),
    .Y(_006_)
  );
  NAND _185_ (
    .A(_009_),
    .B(_052_),
    .Y(_054_)
  );
  NOR _186_ (
    .A(_033_),
    .B(_047_),
    .Y(_055_)
  );
  NOR _187_ (
    .A(_038_),
    .B(_055_),
    .Y(_056_)
  );
  NAND _188_ (
    .A(_044_),
    .B(_055_),
    .Y(_057_)
  );
  NAND _189_ (
    .A(_054_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _190_ (
    .A(_056_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _191_ (
    .A(_022_),
    .B(_059_),
    .Y(_005_)
  );
  NOR _192_ (
    .A(_008_),
    .B(_052_),
    .Y(_060_)
  );
  NOR _193_ (
    .A(_025_),
    .B(_053_),
    .Y(_061_)
  );
  NOR _194_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _195_ (
    .A(_022_),
    .B(_062_),
    .Y(_004_)
  );
  NOR _196_ (
    .A(_023_),
    .B(_021_),
    .Y(_063_)
  );
  NAND _197_ (
    .A(_009_),
    .B(_028_),
    .Y(_064_)
  );
  NAND _198_ (
    .A(_024_),
    .B(_020_),
    .Y(_065_)
  );
  NAND _199_ (
    .A(_025_),
    .B(_019_),
    .Y(_066_)
  );
  NAND _200_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _201_ (
    .A(_064_),
    .B(_067_),
    .Y(_068_)
  );
  NAND _202_ (
    .A(_023_),
    .B(_021_),
    .Y(_069_)
  );
  NOR _203_ (
    .A(_063_),
    .B(_068_),
    .Y(_070_)
  );
  NAND _204_ (
    .A(_086_),
    .B(_069_),
    .Y(_071_)
  );
  NOR _205_ (
    .A(_070_),
    .B(_071_),
    .Y(_003_)
  );
  NOR _206_ (
    .A(_024_),
    .B(_012_),
    .Y(_072_)
  );
  NOR _207_ (
    .A(_025_),
    .B(_011_),
    .Y(_073_)
  );
  NOR _208_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  NAND _209_ (
    .A(_023_),
    .B(_013_),
    .Y(_075_)
  );
  NAND _210_ (
    .A(_024_),
    .B(_012_),
    .Y(_076_)
  );
  NAND _211_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _212_ (
    .A(_074_),
    .B(_077_),
    .Y(_078_)
  );
  NAND _213_ (
    .A(_010_),
    .B(_029_),
    .Y(_079_)
  );
  NAND _214_ (
    .A(_086_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _215_ (
    .A(_078_),
    .B(_080_),
    .Y(_002_)
  );
  NAND _216_ (
    .A(_042_),
    .B(_016_),
    .Y(_081_)
  );
  NAND _217_ (
    .A(_014_),
    .B(_045_),
    .Y(_082_)
  );
  NAND _218_ (
    .A(_031_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _219_ (
    .A(_022_),
    .B(_037_),
    .Y(_084_)
  );
  NAND _220_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _221_ (
    .A(_081_),
    .B(_085_),
    .Y(_007_)
  );
  (* src = "control_logic_synth.v:48.1-73.4" *)
  DFF _222_ (
    .C(clk),
    .D(_092_),
    .Q(counter[0])
  );
  (* src = "control_logic_synth.v:48.1-73.4" *)
  DFF _223_ (
    .C(clk),
    .D(_094_),
    .Q(counter[1])
  );
  (* src = "control_logic_synth.v:48.1-73.4" *)
  DFF _224_ (
    .C(clk),
    .D(_096_),
    .Q(counter[2])
  );
  (* src = "control_logic_synth.v:48.1-73.4" *)
  DFF _225_ (
    .C(clk),
    .D(_098_),
    .Q(error_synth)
  );
  assign _102_[15:1] = { 14'h3fff, counter[2] };
  assign _103_[7:1] = 7'h7f;
  assign { _122_[31:3], _122_[0] } = { 29'h00000000, counter[0] };
  assign _123_[31:1] = { 29'h00000000, counter[2:1] };
  assign { _124_[31:3], _124_[0] } = { 28'h0000000, _122_[2], _123_[0] };
  assign { _133_[31:2], _133_[0] } = { 29'h1fffffff, counter[2], _123_[0] };
  assign _134_[30:0] = { _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], _134_[31], counter[1:0] };
  assign { _143_[30:2], _143_[0] } = { _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], _143_[31], counter[0] };
  assign { _144_[30:3], _144_[0] } = { _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _144_[31], _123_[0] };
  assign _014_ = error_synth;
  assign _086_ = reset_L;
  assign _096_ = _006_;
  assign _010_ = counter[2];
  assign _094_ = _005_;
  assign _009_ = counter[1];
  assign _092_ = _004_;
  assign _008_ = counter[0];
  assign fifo_full_synth = _016_;
  assign fifo_empty_synth = _015_;
  assign _017_ = fifo_rd;
  assign _018_ = fifo_wr;
  assign almost_full_synth = _003_;
  assign almost_empty_synth = _002_;
  assign _019_ = full_threshold[0];
  assign _020_ = full_threshold[1];
  assign _021_ = full_threshold[2];
  assign _011_ = empty_threshold[0];
  assign _012_ = empty_threshold[1];
  assign _013_ = empty_threshold[2];
  assign _098_ = _007_;
endmodule

(* dynports =  1  *)
(* hdlname = "\\memory_synth" *)
(* src = "memory_synth.v:1.1-43.10" *)
module \$paramod\memory_synth\MEM_SIZE=4 (rd_ptr, wr_ptr, data_in_MM, push, pop, reset_L, clk, data_out_MM);
  (* src = "memory_synth.v:19.1-41.4" *)
  wire [5:0] _000_;
  (* src = "memory_synth.v:19.1-41.4" *)
  (* unused_bits = "2" *)
  wire [2:0] _001_;
  (* src = "memory_synth.v:19.1-41.4" *)
  wire [5:0] _002_;
  (* src = "memory_synth.v:19.1-41.4" *)
  wire [5:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _058_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _059_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _060_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _061_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _062_;
  (* src = "memory_synth.v:9.27-9.37" *)
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  (* src = "memory_synth.v:11.11-11.14" *)
  wire _202_;
  (* src = "memory_synth.v:10.11-10.15" *)
  wire _203_;
  (* src = "memory_synth.v:7.23-7.29" *)
  wire _204_;
  (* src = "memory_synth.v:7.23-7.29" *)
  wire _205_;
  (* src = "memory_synth.v:12.11-12.18" *)
  wire _206_;
  (* src = "memory_synth.v:8.23-8.29" *)
  wire _207_;
  (* src = "memory_synth.v:8.23-8.29" *)
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire [5:0] _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire [1:0] _253_;
  wire [1:0] _254_;
  wire [1:0] _255_;
  wire [5:0] _256_;
  wire [5:0] _257_;
  wire _258_;
  wire [5:0] _259_;
  wire [5:0] _260_;
  wire [5:0] _261_;
  wire [5:0] _262_;
  (* src = "memory_synth.v:34.28-34.31" *)
  wire [5:0] _263_;
  wire [5:0] _264_;
  (* unused_bits = "2" *)
  wire [2:0] _265_;
  wire [5:0] \Mem[0] ;
  wire [5:0] \Mem[1] ;
  wire [5:0] \Mem[2] ;
  wire [5:0] \Mem[3] ;
  (* src = "memory_synth.v:13.11-13.14" *)
  input clk;
  (* src = "memory_synth.v:9.27-9.37" *)
  input [5:0] data_in_MM;
  (* src = "memory_synth.v:14.32-14.43" *)
  output [5:0] data_out_MM;
  (* src = "memory_synth.v:17.9-17.10" *)
  wire [31:0] i;
  (* src = "memory_synth.v:11.11-11.14" *)
  input pop;
  (* src = "memory_synth.v:10.11-10.15" *)
  input push;
  (* src = "memory_synth.v:7.23-7.29" *)
  input [2:0] rd_ptr;
  (* src = "memory_synth.v:12.11-12.18" *)
  input reset_L;
  (* src = "memory_synth.v:8.23-8.29" *)
  input [2:0] wr_ptr;
  NOT _266_ (
    .A(_027_),
    .Y(_171_)
  );
  NOT _267_ (
    .A(_026_),
    .Y(_172_)
  );
  NOT _268_ (
    .A(_025_),
    .Y(_173_)
  );
  NOT _269_ (
    .A(_024_),
    .Y(_174_)
  );
  NOT _270_ (
    .A(_023_),
    .Y(_175_)
  );
  NOT _271_ (
    .A(_022_),
    .Y(_176_)
  );
  NOT _272_ (
    .A(_009_),
    .Y(_177_)
  );
  NOT _273_ (
    .A(_008_),
    .Y(_178_)
  );
  NOT _274_ (
    .A(_007_),
    .Y(_179_)
  );
  NOT _275_ (
    .A(_006_),
    .Y(_180_)
  );
  NOT _276_ (
    .A(_005_),
    .Y(_181_)
  );
  NOT _277_ (
    .A(_004_),
    .Y(_182_)
  );
  NOT _278_ (
    .A(_206_),
    .Y(_183_)
  );
  NOT _279_ (
    .A(_207_),
    .Y(_184_)
  );
  NAND _280_ (
    .A(_206_),
    .B(_202_),
    .Y(_185_)
  );
  NOR _281_ (
    .A(_020_),
    .B(_204_),
    .Y(_186_)
  );
  NAND _282_ (
    .A(_172_),
    .B(_204_),
    .Y(_187_)
  );
  NAND _283_ (
    .A(_205_),
    .B(_187_),
    .Y(_188_)
  );
  NOR _284_ (
    .A(_186_),
    .B(_188_),
    .Y(_189_)
  );
  NAND _285_ (
    .A(_014_),
    .B(_204_),
    .Y(_190_)
  );
  NOT _286_ (
    .A(_190_),
    .Y(_191_)
  );
  NOR _287_ (
    .A(_178_),
    .B(_204_),
    .Y(_192_)
  );
  NOR _288_ (
    .A(_191_),
    .B(_192_),
    .Y(_193_)
  );
  NOR _289_ (
    .A(_205_),
    .B(_193_),
    .Y(_194_)
  );
  NOR _290_ (
    .A(_189_),
    .B(_194_),
    .Y(_195_)
  );
  NOR _291_ (
    .A(_185_),
    .B(_195_),
    .Y(_056_)
  );
  NOR _292_ (
    .A(_019_),
    .B(_204_),
    .Y(_196_)
  );
  NAND _293_ (
    .A(_173_),
    .B(_204_),
    .Y(_197_)
  );
  NAND _294_ (
    .A(_205_),
    .B(_197_),
    .Y(_198_)
  );
  NOR _295_ (
    .A(_196_),
    .B(_198_),
    .Y(_199_)
  );
  NAND _296_ (
    .A(_013_),
    .B(_204_),
    .Y(_200_)
  );
  NOT _297_ (
    .A(_200_),
    .Y(_201_)
  );
  NOR _298_ (
    .A(_179_),
    .B(_204_),
    .Y(_064_)
  );
  NOR _299_ (
    .A(_201_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _300_ (
    .A(_205_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _301_ (
    .A(_199_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _302_ (
    .A(_185_),
    .B(_067_),
    .Y(_055_)
  );
  NOR _303_ (
    .A(_018_),
    .B(_204_),
    .Y(_068_)
  );
  NAND _304_ (
    .A(_174_),
    .B(_204_),
    .Y(_069_)
  );
  NAND _305_ (
    .A(_205_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _306_ (
    .A(_068_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _307_ (
    .A(_012_),
    .B(_204_),
    .Y(_072_)
  );
  NOT _308_ (
    .A(_072_),
    .Y(_073_)
  );
  NOR _309_ (
    .A(_180_),
    .B(_204_),
    .Y(_074_)
  );
  NOR _310_ (
    .A(_073_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _311_ (
    .A(_205_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _312_ (
    .A(_071_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _313_ (
    .A(_185_),
    .B(_077_),
    .Y(_054_)
  );
  NOR _314_ (
    .A(_017_),
    .B(_204_),
    .Y(_078_)
  );
  NAND _315_ (
    .A(_175_),
    .B(_204_),
    .Y(_079_)
  );
  NAND _316_ (
    .A(_205_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _317_ (
    .A(_078_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _318_ (
    .A(_011_),
    .B(_204_),
    .Y(_082_)
  );
  NOT _319_ (
    .A(_082_),
    .Y(_083_)
  );
  NOR _320_ (
    .A(_181_),
    .B(_204_),
    .Y(_084_)
  );
  NOR _321_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _322_ (
    .A(_205_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _323_ (
    .A(_081_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _324_ (
    .A(_185_),
    .B(_087_),
    .Y(_053_)
  );
  NOR _325_ (
    .A(_016_),
    .B(_204_),
    .Y(_088_)
  );
  NAND _326_ (
    .A(_176_),
    .B(_204_),
    .Y(_089_)
  );
  NAND _327_ (
    .A(_205_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _328_ (
    .A(_088_),
    .B(_090_),
    .Y(_091_)
  );
  NAND _329_ (
    .A(_010_),
    .B(_204_),
    .Y(_092_)
  );
  NOT _330_ (
    .A(_092_),
    .Y(_093_)
  );
  NOR _331_ (
    .A(_182_),
    .B(_204_),
    .Y(_094_)
  );
  NOR _332_ (
    .A(_093_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _333_ (
    .A(_205_),
    .B(_095_),
    .Y(_096_)
  );
  NOR _334_ (
    .A(_091_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _335_ (
    .A(_185_),
    .B(_097_),
    .Y(_052_)
  );
  NAND _336_ (
    .A(_203_),
    .B(_208_),
    .Y(_098_)
  );
  NOT _337_ (
    .A(_098_),
    .Y(_099_)
  );
  NOR _338_ (
    .A(_184_),
    .B(_098_),
    .Y(_100_)
  );
  NAND _339_ (
    .A(_207_),
    .B(_099_),
    .Y(_101_)
  );
  NOR _340_ (
    .A(_183_),
    .B(_100_),
    .Y(_102_)
  );
  NAND _341_ (
    .A(_027_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _342_ (
    .A(_183_),
    .B(_101_),
    .Y(_104_)
  );
  NAND _343_ (
    .A(_063_),
    .B(_104_),
    .Y(_105_)
  );
  NAND _344_ (
    .A(_103_),
    .B(_105_),
    .Y(_051_)
  );
  NAND _345_ (
    .A(_026_),
    .B(_102_),
    .Y(_106_)
  );
  NAND _346_ (
    .A(_062_),
    .B(_104_),
    .Y(_107_)
  );
  NAND _347_ (
    .A(_106_),
    .B(_107_),
    .Y(_050_)
  );
  NAND _348_ (
    .A(_025_),
    .B(_102_),
    .Y(_108_)
  );
  NAND _349_ (
    .A(_061_),
    .B(_104_),
    .Y(_109_)
  );
  NAND _350_ (
    .A(_108_),
    .B(_109_),
    .Y(_049_)
  );
  NAND _351_ (
    .A(_024_),
    .B(_102_),
    .Y(_110_)
  );
  NAND _352_ (
    .A(_060_),
    .B(_104_),
    .Y(_111_)
  );
  NAND _353_ (
    .A(_110_),
    .B(_111_),
    .Y(_048_)
  );
  NAND _354_ (
    .A(_023_),
    .B(_102_),
    .Y(_112_)
  );
  NAND _355_ (
    .A(_059_),
    .B(_104_),
    .Y(_113_)
  );
  NAND _356_ (
    .A(_112_),
    .B(_113_),
    .Y(_047_)
  );
  NAND _357_ (
    .A(_022_),
    .B(_102_),
    .Y(_114_)
  );
  NAND _358_ (
    .A(_058_),
    .B(_104_),
    .Y(_115_)
  );
  NAND _359_ (
    .A(_114_),
    .B(_115_),
    .Y(_046_)
  );
  NAND _360_ (
    .A(_206_),
    .B(_184_),
    .Y(_116_)
  );
  NOR _361_ (
    .A(_098_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _362_ (
    .A(_183_),
    .B(_117_),
    .Y(_118_)
  );
  NAND _363_ (
    .A(_021_),
    .B(_118_),
    .Y(_119_)
  );
  NAND _364_ (
    .A(_063_),
    .B(_117_),
    .Y(_120_)
  );
  NAND _365_ (
    .A(_119_),
    .B(_120_),
    .Y(_045_)
  );
  NAND _366_ (
    .A(_020_),
    .B(_118_),
    .Y(_121_)
  );
  NAND _367_ (
    .A(_062_),
    .B(_117_),
    .Y(_122_)
  );
  NAND _368_ (
    .A(_121_),
    .B(_122_),
    .Y(_044_)
  );
  NAND _369_ (
    .A(_019_),
    .B(_118_),
    .Y(_123_)
  );
  NAND _370_ (
    .A(_061_),
    .B(_117_),
    .Y(_124_)
  );
  NAND _371_ (
    .A(_123_),
    .B(_124_),
    .Y(_043_)
  );
  NAND _372_ (
    .A(_018_),
    .B(_118_),
    .Y(_125_)
  );
  NAND _373_ (
    .A(_060_),
    .B(_117_),
    .Y(_126_)
  );
  NAND _374_ (
    .A(_125_),
    .B(_126_),
    .Y(_042_)
  );
  NAND _375_ (
    .A(_017_),
    .B(_118_),
    .Y(_127_)
  );
  NAND _376_ (
    .A(_059_),
    .B(_117_),
    .Y(_128_)
  );
  NAND _377_ (
    .A(_127_),
    .B(_128_),
    .Y(_041_)
  );
  NAND _378_ (
    .A(_016_),
    .B(_118_),
    .Y(_129_)
  );
  NAND _379_ (
    .A(_058_),
    .B(_117_),
    .Y(_130_)
  );
  NAND _380_ (
    .A(_129_),
    .B(_130_),
    .Y(_040_)
  );
  NOR _381_ (
    .A(_183_),
    .B(_208_),
    .Y(_131_)
  );
  NAND _382_ (
    .A(_203_),
    .B(_131_),
    .Y(_132_)
  );
  NOR _383_ (
    .A(_184_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _384_ (
    .A(_183_),
    .B(_133_),
    .Y(_134_)
  );
  NAND _385_ (
    .A(_015_),
    .B(_134_),
    .Y(_135_)
  );
  NAND _386_ (
    .A(_063_),
    .B(_133_),
    .Y(_136_)
  );
  NAND _387_ (
    .A(_135_),
    .B(_136_),
    .Y(_039_)
  );
  NAND _388_ (
    .A(_014_),
    .B(_134_),
    .Y(_137_)
  );
  NAND _389_ (
    .A(_062_),
    .B(_133_),
    .Y(_138_)
  );
  NAND _390_ (
    .A(_137_),
    .B(_138_),
    .Y(_038_)
  );
  NAND _391_ (
    .A(_013_),
    .B(_134_),
    .Y(_139_)
  );
  NAND _392_ (
    .A(_061_),
    .B(_133_),
    .Y(_140_)
  );
  NAND _393_ (
    .A(_139_),
    .B(_140_),
    .Y(_037_)
  );
  NAND _394_ (
    .A(_012_),
    .B(_134_),
    .Y(_141_)
  );
  NAND _395_ (
    .A(_060_),
    .B(_133_),
    .Y(_142_)
  );
  NAND _396_ (
    .A(_141_),
    .B(_142_),
    .Y(_036_)
  );
  NAND _397_ (
    .A(_011_),
    .B(_134_),
    .Y(_143_)
  );
  NAND _398_ (
    .A(_059_),
    .B(_133_),
    .Y(_144_)
  );
  NAND _399_ (
    .A(_143_),
    .B(_144_),
    .Y(_035_)
  );
  NAND _400_ (
    .A(_010_),
    .B(_134_),
    .Y(_145_)
  );
  NAND _401_ (
    .A(_058_),
    .B(_133_),
    .Y(_146_)
  );
  NAND _402_ (
    .A(_145_),
    .B(_146_),
    .Y(_034_)
  );
  NOR _403_ (
    .A(_207_),
    .B(_132_),
    .Y(_147_)
  );
  NOR _404_ (
    .A(_183_),
    .B(_147_),
    .Y(_148_)
  );
  NAND _405_ (
    .A(_009_),
    .B(_148_),
    .Y(_149_)
  );
  NAND _406_ (
    .A(_063_),
    .B(_147_),
    .Y(_150_)
  );
  NAND _407_ (
    .A(_149_),
    .B(_150_),
    .Y(_033_)
  );
  NAND _408_ (
    .A(_008_),
    .B(_148_),
    .Y(_151_)
  );
  NAND _409_ (
    .A(_062_),
    .B(_147_),
    .Y(_152_)
  );
  NAND _410_ (
    .A(_151_),
    .B(_152_),
    .Y(_032_)
  );
  NAND _411_ (
    .A(_007_),
    .B(_148_),
    .Y(_153_)
  );
  NAND _412_ (
    .A(_061_),
    .B(_147_),
    .Y(_154_)
  );
  NAND _413_ (
    .A(_153_),
    .B(_154_),
    .Y(_031_)
  );
  NAND _414_ (
    .A(_006_),
    .B(_148_),
    .Y(_155_)
  );
  NAND _415_ (
    .A(_060_),
    .B(_147_),
    .Y(_156_)
  );
  NAND _416_ (
    .A(_155_),
    .B(_156_),
    .Y(_030_)
  );
  NAND _417_ (
    .A(_005_),
    .B(_148_),
    .Y(_157_)
  );
  NAND _418_ (
    .A(_059_),
    .B(_147_),
    .Y(_158_)
  );
  NAND _419_ (
    .A(_157_),
    .B(_158_),
    .Y(_029_)
  );
  NAND _420_ (
    .A(_004_),
    .B(_148_),
    .Y(_159_)
  );
  NAND _421_ (
    .A(_058_),
    .B(_147_),
    .Y(_160_)
  );
  NAND _422_ (
    .A(_159_),
    .B(_160_),
    .Y(_028_)
  );
  NOR _423_ (
    .A(_021_),
    .B(_204_),
    .Y(_161_)
  );
  NAND _424_ (
    .A(_171_),
    .B(_204_),
    .Y(_162_)
  );
  NAND _425_ (
    .A(_205_),
    .B(_162_),
    .Y(_163_)
  );
  NOR _426_ (
    .A(_161_),
    .B(_163_),
    .Y(_164_)
  );
  NAND _427_ (
    .A(_015_),
    .B(_204_),
    .Y(_165_)
  );
  NOT _428_ (
    .A(_165_),
    .Y(_166_)
  );
  NOR _429_ (
    .A(_177_),
    .B(_204_),
    .Y(_167_)
  );
  NOR _430_ (
    .A(_166_),
    .B(_167_),
    .Y(_168_)
  );
  NOR _431_ (
    .A(_205_),
    .B(_168_),
    .Y(_169_)
  );
  NOR _432_ (
    .A(_164_),
    .B(_169_),
    .Y(_170_)
  );
  NOR _433_ (
    .A(_185_),
    .B(_170_),
    .Y(_057_)
  );
  DFF _434_ (
    .C(clk),
    .D(_223_),
    .Q(\Mem[0] [0])
  );
  DFF _435_ (
    .C(clk),
    .D(_224_),
    .Q(\Mem[0] [1])
  );
  DFF _436_ (
    .C(clk),
    .D(_225_),
    .Q(\Mem[0] [2])
  );
  DFF _437_ (
    .C(clk),
    .D(_226_),
    .Q(\Mem[0] [3])
  );
  DFF _438_ (
    .C(clk),
    .D(_227_),
    .Q(\Mem[0] [4])
  );
  DFF _439_ (
    .C(clk),
    .D(_228_),
    .Q(\Mem[0] [5])
  );
  DFF _440_ (
    .C(clk),
    .D(_229_),
    .Q(\Mem[1] [0])
  );
  DFF _441_ (
    .C(clk),
    .D(_230_),
    .Q(\Mem[1] [1])
  );
  DFF _442_ (
    .C(clk),
    .D(_231_),
    .Q(\Mem[1] [2])
  );
  DFF _443_ (
    .C(clk),
    .D(_232_),
    .Q(\Mem[1] [3])
  );
  DFF _444_ (
    .C(clk),
    .D(_233_),
    .Q(\Mem[1] [4])
  );
  DFF _445_ (
    .C(clk),
    .D(_234_),
    .Q(\Mem[1] [5])
  );
  DFF _446_ (
    .C(clk),
    .D(_235_),
    .Q(\Mem[2] [0])
  );
  DFF _447_ (
    .C(clk),
    .D(_236_),
    .Q(\Mem[2] [1])
  );
  DFF _448_ (
    .C(clk),
    .D(_237_),
    .Q(\Mem[2] [2])
  );
  DFF _449_ (
    .C(clk),
    .D(_238_),
    .Q(\Mem[2] [3])
  );
  DFF _450_ (
    .C(clk),
    .D(_239_),
    .Q(\Mem[2] [4])
  );
  DFF _451_ (
    .C(clk),
    .D(_240_),
    .Q(\Mem[2] [5])
  );
  DFF _452_ (
    .C(clk),
    .D(_241_),
    .Q(\Mem[3] [0])
  );
  DFF _453_ (
    .C(clk),
    .D(_242_),
    .Q(\Mem[3] [1])
  );
  DFF _454_ (
    .C(clk),
    .D(_243_),
    .Q(\Mem[3] [2])
  );
  DFF _455_ (
    .C(clk),
    .D(_244_),
    .Q(\Mem[3] [3])
  );
  DFF _456_ (
    .C(clk),
    .D(_245_),
    .Q(\Mem[3] [4])
  );
  DFF _457_ (
    .C(clk),
    .D(_246_),
    .Q(\Mem[3] [5])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _458_ (
    .C(clk),
    .D(_247_),
    .Q(data_out_MM[0])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _459_ (
    .C(clk),
    .D(_248_),
    .Q(data_out_MM[1])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _460_ (
    .C(clk),
    .D(_249_),
    .Q(data_out_MM[2])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _461_ (
    .C(clk),
    .D(_250_),
    .Q(data_out_MM[3])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _462_ (
    .C(clk),
    .D(_251_),
    .Q(data_out_MM[4])
  );
  (* src = "memory_synth.v:19.1-41.4" *)
  DFF _463_ (
    .C(clk),
    .D(_252_),
    .Q(data_out_MM[5])
  );
  assign _000_[4:0] = { _000_[5], _000_[5], _000_[5], _000_[5], _000_[5] };
  assign _003_[4:0] = { _003_[5], _003_[5], _003_[5], _003_[5], _003_[5] };
  assign _253_[0] = _000_[5];
  assign _254_[0] = _000_[5];
  assign _255_[0] = _000_[5];
  assign _259_[4:0] = { _259_[5], _259_[5], _259_[5], _259_[5], _259_[5] };
  assign i = 32'd4;
  assign _251_ = _056_;
  assign _250_ = _055_;
  assign _249_ = _054_;
  assign _248_ = _053_;
  assign _247_ = _052_;
  assign _027_ = \Mem[3] [5];
  assign _246_ = _051_;
  assign _026_ = \Mem[3] [4];
  assign _245_ = _050_;
  assign _025_ = \Mem[3] [3];
  assign _244_ = _049_;
  assign _024_ = \Mem[3] [2];
  assign _243_ = _048_;
  assign _023_ = \Mem[3] [1];
  assign _242_ = _047_;
  assign _022_ = \Mem[3] [0];
  assign _241_ = _046_;
  assign _021_ = \Mem[2] [5];
  assign _240_ = _045_;
  assign _020_ = \Mem[2] [4];
  assign _239_ = _044_;
  assign _019_ = \Mem[2] [3];
  assign _238_ = _043_;
  assign _018_ = \Mem[2] [2];
  assign _237_ = _042_;
  assign _017_ = \Mem[2] [1];
  assign _236_ = _041_;
  assign _016_ = \Mem[2] [0];
  assign _235_ = _040_;
  assign _015_ = \Mem[1] [5];
  assign _234_ = _039_;
  assign _014_ = \Mem[1] [4];
  assign _233_ = _038_;
  assign _013_ = \Mem[1] [3];
  assign _232_ = _037_;
  assign _012_ = \Mem[1] [2];
  assign _231_ = _036_;
  assign _011_ = \Mem[1] [1];
  assign _230_ = _035_;
  assign _010_ = \Mem[1] [0];
  assign _229_ = _034_;
  assign _009_ = \Mem[0] [5];
  assign _228_ = _033_;
  assign _008_ = \Mem[0] [4];
  assign _227_ = _032_;
  assign _007_ = \Mem[0] [3];
  assign _226_ = _031_;
  assign _006_ = \Mem[0] [2];
  assign _225_ = _030_;
  assign _005_ = \Mem[0] [1];
  assign _224_ = _029_;
  assign _004_ = \Mem[0] [0];
  assign _223_ = _028_;
  assign _206_ = reset_L;
  assign _202_ = pop;
  assign _058_ = data_in_MM[0];
  assign _203_ = push;
  assign _059_ = data_in_MM[1];
  assign _060_ = data_in_MM[2];
  assign _061_ = data_in_MM[3];
  assign _062_ = data_in_MM[4];
  assign _063_ = data_in_MM[5];
  assign _204_ = rd_ptr[0];
  assign _205_ = rd_ptr[1];
  assign _207_ = wr_ptr[0];
  assign _208_ = wr_ptr[1];
  assign _252_ = _057_;
endmodule

(* dynports =  1  *)
(* hdlname = "\\read_logic_synth" *)
(* src = "read_logic_synth.v:1.1-49.10" *)
module \$paramod\read_logic_synth\MEM_SIZE=4 (fifo_rd, fifo_wr, fifo_empty_synth, clk, reset_L, rd_ptr, pop);
  (* src = "read_logic_synth.v:18.1-31.4" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "read_logic_synth.v:10.11-10.21" *)
  wire _04_;
  (* src = "read_logic_synth.v:8.11-8.18" *)
  wire _05_;
  (* src = "read_logic_synth.v:9.11-9.18" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  (* src = "read_logic_synth.v:14.16-14.19" *)
  wire _19_;
  (* src = "read_logic_synth.v:13.28-13.34" *)
  wire _20_;
  (* src = "read_logic_synth.v:13.28-13.34" *)
  wire _21_;
  (* src = "read_logic_synth.v:13.28-13.34" *)
  wire _22_;
  (* src = "read_logic_synth.v:12.11-12.18" *)
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  (* src = "read_logic_synth.v:20.14-20.36" *)
  wire _33_;
  (* src = "read_logic_synth.v:20.42-20.60" *)
  wire _34_;
  (* src = "read_logic_synth.v:20.25-20.36" *)
  wire _35_;
  wire [2:0] _36_;
  (* force_downto = 32'd1 *)
  (* src = "read_logic_synth.v:41.23-41.33|write_logic_synth.v:39.23-39.33|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _37_;
  (* force_downto = 32'd1 *)
  (* src = "read_logic_synth.v:41.23-41.33|write_logic_synth.v:39.23-39.33|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _38_;
  (* force_downto = 32'd1 *)
  (* src = "read_logic_synth.v:41.23-41.33|write_logic_synth.v:39.23-39.33|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [31:0] _39_;
  (* src = "read_logic_synth.v:11.11-11.14" *)
  input clk;
  (* src = "read_logic_synth.v:10.11-10.21" *)
  input fifo_empty_synth;
  (* src = "read_logic_synth.v:8.11-8.18" *)
  input fifo_rd;
  (* src = "read_logic_synth.v:9.11-9.18" *)
  input fifo_wr;
  (* src = "read_logic_synth.v:14.16-14.19" *)
  output pop;
  (* src = "read_logic_synth.v:13.28-13.34" *)
  output [2:0] rd_ptr;
  (* src = "read_logic_synth.v:12.11-12.18" *)
  input reset_L;
  NOT _40_ (
    .A(_22_),
    .Y(_07_)
  );
  NOT _41_ (
    .A(_23_),
    .Y(_08_)
  );
  NOT _42_ (
    .A(_20_),
    .Y(_09_)
  );
  NOT _43_ (
    .A(_06_),
    .Y(_10_)
  );
  NAND _44_ (
    .A(_04_),
    .B(_10_),
    .Y(_11_)
  );
  NAND _45_ (
    .A(_05_),
    .B(_11_),
    .Y(_12_)
  );
  NOR _46_ (
    .A(_09_),
    .B(_12_),
    .Y(_13_)
  );
  NOR _47_ (
    .A(_21_),
    .B(_13_),
    .Y(_14_)
  );
  NAND _48_ (
    .A(_21_),
    .B(_13_),
    .Y(_15_)
  );
  NAND _49_ (
    .A(_23_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _50_ (
    .A(_14_),
    .B(_16_),
    .Y(_02_)
  );
  NAND _51_ (
    .A(_09_),
    .B(_12_),
    .Y(_17_)
  );
  NAND _52_ (
    .A(_23_),
    .B(_17_),
    .Y(_18_)
  );
  NOR _53_ (
    .A(_13_),
    .B(_18_),
    .Y(_01_)
  );
  NOR _54_ (
    .A(_08_),
    .B(_12_),
    .Y(_19_)
  );
  NOR _55_ (
    .A(_07_),
    .B(_16_),
    .Y(_03_)
  );
  (* src = "read_logic_synth.v:35.1-47.4" *)
  DFF _56_ (
    .C(clk),
    .D(_26_),
    .Q(rd_ptr[0])
  );
  (* src = "read_logic_synth.v:35.1-47.4" *)
  DFF _57_ (
    .C(clk),
    .D(_28_),
    .Q(rd_ptr[1])
  );
  (* src = "read_logic_synth.v:35.1-47.4" *)
  DFF _58_ (
    .C(clk),
    .D(_30_),
    .Q(rd_ptr[2])
  );
  assign { _37_[31:3], _37_[0] } = { 29'h00000000, rd_ptr[0] };
  assign _38_[31:1] = { 29'h00000000, rd_ptr[2:1] };
  assign { _39_[31:3], _39_[0] } = { 28'h0000000, _37_[2], _38_[0] };
  assign _22_ = rd_ptr[2];
  assign _23_ = reset_L;
  assign _28_ = _02_;
  assign _21_ = rd_ptr[1];
  assign _26_ = _01_;
  assign _20_ = rd_ptr[0];
  assign _04_ = fifo_empty_synth;
  assign _05_ = fifo_rd;
  assign _06_ = fifo_wr;
  assign pop = _19_;
  assign _30_ = _03_;
endmodule

(* dynports =  1  *)
(* hdlname = "\\write_logic_synth" *)
(* src = "write_logic_synth.v:1.1-49.10" *)
module \$paramod\write_logic_synth\MEM_SIZE=4 (fifo_wr, fifo_rd, fifo_full_synth, clk, reset_L, wr_ptr, push);
  (* src = "write_logic_synth.v:18.1-30.4" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  (* src = "write_logic_synth.v:10.11-10.20" *)
  wire _04_;
  (* src = "write_logic_synth.v:9.11-9.18" *)
  wire _05_;
  (* src = "write_logic_synth.v:8.11-8.18" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  (* src = "write_logic_synth.v:14.16-14.20" *)
  wire _19_;
  (* src = "write_logic_synth.v:12.11-12.18" *)
  wire _20_;
  (* src = "write_logic_synth.v:13.28-13.34" *)
  wire _21_;
  (* src = "write_logic_synth.v:13.28-13.34" *)
  wire _22_;
  (* src = "write_logic_synth.v:13.28-13.34" *)
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  (* src = "write_logic_synth.v:20.14-20.35" *)
  wire _33_;
  (* src = "write_logic_synth.v:20.41-20.59" *)
  wire _34_;
  (* src = "write_logic_synth.v:20.25-20.35" *)
  wire _35_;
  wire [2:0] _36_;
  (* force_downto = 32'd1 *)
  (* src = "write_logic_synth.v:39.23-39.33|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [31:0] _37_;
  (* force_downto = 32'd1 *)
  (* src = "write_logic_synth.v:39.23-39.33|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _38_;
  (* force_downto = 32'd1 *)
  (* src = "write_logic_synth.v:39.23-39.33|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "3" *)
  wire [31:0] _39_;
  (* src = "write_logic_synth.v:11.11-11.14" *)
  input clk;
  (* src = "write_logic_synth.v:10.11-10.20" *)
  input fifo_full_synth;
  (* src = "write_logic_synth.v:9.11-9.18" *)
  input fifo_rd;
  (* src = "write_logic_synth.v:8.11-8.18" *)
  input fifo_wr;
  (* src = "write_logic_synth.v:14.16-14.20" *)
  output push;
  (* src = "write_logic_synth.v:12.11-12.18" *)
  input reset_L;
  (* src = "write_logic_synth.v:13.28-13.34" *)
  output [2:0] wr_ptr;
  NOT _40_ (
    .A(_23_),
    .Y(_07_)
  );
  NOT _41_ (
    .A(_20_),
    .Y(_08_)
  );
  NOT _42_ (
    .A(_21_),
    .Y(_09_)
  );
  NOT _43_ (
    .A(_05_),
    .Y(_10_)
  );
  NAND _44_ (
    .A(_04_),
    .B(_10_),
    .Y(_11_)
  );
  NAND _45_ (
    .A(_06_),
    .B(_11_),
    .Y(_12_)
  );
  NOR _46_ (
    .A(_09_),
    .B(_12_),
    .Y(_13_)
  );
  NOR _47_ (
    .A(_22_),
    .B(_13_),
    .Y(_14_)
  );
  NAND _48_ (
    .A(_22_),
    .B(_13_),
    .Y(_15_)
  );
  NAND _49_ (
    .A(_20_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _50_ (
    .A(_14_),
    .B(_16_),
    .Y(_02_)
  );
  NAND _51_ (
    .A(_09_),
    .B(_12_),
    .Y(_17_)
  );
  NAND _52_ (
    .A(_20_),
    .B(_17_),
    .Y(_18_)
  );
  NOR _53_ (
    .A(_13_),
    .B(_18_),
    .Y(_01_)
  );
  NOR _54_ (
    .A(_08_),
    .B(_12_),
    .Y(_19_)
  );
  NOR _55_ (
    .A(_07_),
    .B(_16_),
    .Y(_03_)
  );
  (* src = "write_logic_synth.v:33.1-45.4" *)
  DFF _56_ (
    .C(clk),
    .D(_26_),
    .Q(wr_ptr[0])
  );
  (* src = "write_logic_synth.v:33.1-45.4" *)
  DFF _57_ (
    .C(clk),
    .D(_28_),
    .Q(wr_ptr[1])
  );
  (* src = "write_logic_synth.v:33.1-45.4" *)
  DFF _58_ (
    .C(clk),
    .D(_30_),
    .Q(wr_ptr[2])
  );
  assign { _37_[31:3], _37_[0] } = { 29'h00000000, wr_ptr[0] };
  assign _38_[31:1] = { 29'h00000000, wr_ptr[2:1] };
  assign { _39_[31:3], _39_[0] } = { 28'h0000000, _37_[2], _38_[0] };
  assign _23_ = wr_ptr[2];
  assign _20_ = reset_L;
  assign _28_ = _02_;
  assign _22_ = wr_ptr[1];
  assign _26_ = _01_;
  assign _21_ = wr_ptr[0];
  assign _04_ = fifo_full_synth;
  assign _06_ = fifo_wr;
  assign _05_ = fifo_rd;
  assign push = _19_;
  assign _30_ = _03_;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "fifo.v:1.1-87.10" *)
module fifo_synth(fifo_data_out_synth, error_synth, almost_empty_synth, almost_full_synth, fifo_full_synth, fifo_empty_synth, fifo_wr, fifo_rd, fifo_data_in, full_threshold, empty_threshold, clk, reset_L);
  (* src = "fifo.v:10.12-10.24" *)
  output almost_empty_synth;
  (* src = "fifo.v:11.12-11.23" *)
  output almost_full_synth;
  (* src = "fifo.v:19.11-19.14" *)
  input clk;
  (* src = "fifo.v:80.24-80.34" *)
  wire [5:0] data_in_MM;
  (* src = "fifo.v:24.22-24.33" *)
  wire [5:0] data_out_MM;
  (* src = "fifo.v:18.23-18.38" *)
  input [2:0] empty_threshold;
  (* src = "fifo.v:9.12-9.17" *)
  output error_synth;
  (* src = "fifo.v:16.27-16.39" *)
  input [5:0] fifo_data_in;
  (* src = "fifo.v:8.32-8.45" *)
  output [5:0] fifo_data_out_synth;
  (* src = "fifo.v:13.12-13.22" *)
  output fifo_empty_synth;
  (* src = "fifo.v:12.12-12.21" *)
  output fifo_full_synth;
  (* src = "fifo.v:15.11-15.18" *)
  input fifo_rd;
  (* src = "fifo.v:14.11-14.18" *)
  input fifo_wr;
  (* src = "fifo.v:17.23-17.37" *)
  input [2:0] full_threshold;
  (* src = "fifo.v:25.8-25.11" *)
  wire pop;
  (* src = "fifo.v:26.8-26.12" *)
  wire push;
  (* src = "fifo.v:27.18-27.24" *)
  wire [2:0] rd_ptr;
  (* src = "fifo.v:20.11-20.18" *)
  input reset_L;
  (* src = "fifo.v:28.18-28.24" *)
  wire [2:0] wr_ptr;
  (* src = "fifo.v:53.38-66.28" *)
  \$paramod\control_logic_synth\MEM_SIZE=4  control_log (
    .almost_empty_synth(almost_empty_synth),
    .almost_full_synth(almost_full_synth),
    .clk(clk),
    .empty_threshold(empty_threshold),
    .error_synth(error_synth),
    .fifo_empty_synth(fifo_empty_synth),
    .fifo_full_synth(fifo_full_synth),
    .fifo_rd(fifo_rd),
    .fifo_wr(fifo_wr),
    .full_threshold(full_threshold),
    .reset_L(reset_L)
  );
  (* src = "fifo.v:68.31-78.23" *)
  \$paramod\memory_synth\MEM_SIZE=4  memoria (
    .clk(clk),
    .data_in_MM(fifo_data_in),
    .data_out_MM(data_out_MM),
    .pop(pop),
    .push(push),
    .rd_ptr(rd_ptr),
    .reset_L(reset_L),
    .wr_ptr(wr_ptr)
  );
  (* src = "fifo.v:42.35-51.29" *)
  \$paramod\read_logic_synth\MEM_SIZE=4  read_log (
    .clk(clk),
    .fifo_empty_synth(fifo_empty_synth),
    .fifo_rd(fifo_rd),
    .fifo_wr(fifo_wr),
    .pop(pop),
    .rd_ptr(rd_ptr),
    .reset_L(reset_L)
  );
  (* src = "fifo.v:31.36-40.31" *)
  \$paramod\write_logic_synth\MEM_SIZE=4  write_log (
    .clk(clk),
    .fifo_full_synth(fifo_full_synth),
    .fifo_rd(fifo_rd),
    .fifo_wr(fifo_wr),
    .push(push),
    .reset_L(reset_L),
    .wr_ptr(wr_ptr)
  );
  assign data_in_MM = fifo_data_in;
  assign fifo_data_out_synth = data_out_MM;
endmodule
