/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.3.0-18+deb9u1 -O2 -fdebug-prefix-map=/build/yosys-XOsRIM/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "maquina.v:1" *)
module maquina_E(clk, reset, init, Umbrales_MFs, Umbrales_VCs, Umbrales_Ds, FIFO_empties, FIFO_errors, Umbrales_MFs_internos, Umbrales_VCs_internos, Umbrales_Ds_internos, error_out_E, active_out_E, idle_out_E);
  (* src = "maquina.v:8" *)
  input [4:0] FIFO_empties;
  (* src = "maquina.v:9" *)
  input [4:0] FIFO_errors;
  (* src = "maquina.v:7" *)
  input [1:0] Umbrales_Ds;
  (* src = "maquina.v:12" *)
  output [1:0] Umbrales_Ds_internos;
  (* src = "maquina.v:5" *)
  input [1:0] Umbrales_MFs;
  (* src = "maquina.v:10" *)
  output [1:0] Umbrales_MFs_internos;
  (* src = "maquina.v:6" *)
  input [1:0] Umbrales_VCs;
  (* src = "maquina.v:11" *)
  output [1:0] Umbrales_VCs_internos;
  (* src = "maquina.v:14" *)
  output active_out_E;
  (* src = "maquina.v:2" *)
  input clk;
  (* src = "maquina.v:13" *)
  output error_out_E;
  (* src = "maquina.v:15" *)
  output idle_out_E;
  (* src = "maquina.v:4" *)
  input init;
  (* src = "maquina.v:3" *)
  input reset;
  assign Umbrales_Ds_internos = 2'b00;
  assign Umbrales_MFs_internos = 2'b00;
  assign Umbrales_VCs_internos = 2'b00;
  assign active_out_E = 1'b0;
  assign error_out_E = 1'b0;
  assign idle_out_E = 1'b0;
endmodule
