/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.3.0-18+deb9u1 -O2 -fdebug-prefix-map=/build/yosys-XOsRIM/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "maquina.v:1" *)
module maquina_synth(clk, reset, init, Umbral_MF_alto, Umbral_MF_bajo, Umbral_VC_alto, Umbral_VC_bajo, Umbral_D_alto, Umbral_D_bajo, FIFO_empties, FIFO_errors, Umbral_MF_alto_interno_synth, Umbral_MF_bajo_interno_synth, Umbral_VC_alto_interno_synth, Umbral_VC_bajo_interno_synth, Umbral_D_alto_interno_synth, Umbral_D_bajo_interno_synth, error_out_synth, errors_out_synth, active_out_synth, idle_out_synth);
  (* src = "maquina.v:47" *)
  wire [4:0] _000_;
  (* src = "maquina.v:47" *)
  wire [1:0] _001_;
  (* src = "maquina.v:47" *)
  wire [1:0] _002_;
  (* src = "maquina.v:47" *)
  wire [1:0] _003_;
  (* src = "maquina.v:47" *)
  wire [1:0] _004_;
  (* src = "maquina.v:47" *)
  wire [1:0] _005_;
  (* src = "maquina.v:47" *)
  wire [1:0] _006_;
  (* src = "maquina.v:47" *)
  wire _007_;
  (* src = "maquina.v:47" *)
  wire _008_;
  (* src = "maquina.v:47" *)
  wire [4:0] _009_;
  (* src = "maquina.v:47" *)
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  (* src = "maquina.v:11" *)
  input [4:0] FIFO_empties;
  (* src = "maquina.v:12" *)
  input [4:0] FIFO_errors;
  (* src = "maquina.v:39" *)
  wire [4:0] FIFO_errors_temp;
  (* src = "maquina.v:9" *)
  input [1:0] Umbral_D_alto;
  (* src = "maquina.v:17" *)
  output [1:0] Umbral_D_alto_interno_synth;
  (* src = "maquina.v:10" *)
  input [1:0] Umbral_D_bajo;
  (* src = "maquina.v:18" *)
  output [1:0] Umbral_D_bajo_interno_synth;
  (* src = "maquina.v:5" *)
  input [1:0] Umbral_MF_alto;
  (* src = "maquina.v:13" *)
  output [1:0] Umbral_MF_alto_interno_synth;
  (* src = "maquina.v:6" *)
  input [1:0] Umbral_MF_bajo;
  (* src = "maquina.v:14" *)
  output [1:0] Umbral_MF_bajo_interno_synth;
  (* src = "maquina.v:7" *)
  input [1:0] Umbral_VC_alto;
  (* src = "maquina.v:15" *)
  output [1:0] Umbral_VC_alto_interno_synth;
  (* src = "maquina.v:8" *)
  input [1:0] Umbral_VC_bajo;
  (* src = "maquina.v:16" *)
  output [1:0] Umbral_VC_bajo_interno_synth;
  (* src = "maquina.v:21" *)
  output active_out_synth;
  (* src = "maquina.v:35" *)
  wire active_out_synth_temp;
  (* src = "maquina.v:2" *)
  input clk;
  (* src = "maquina.v:19" *)
  output error_out_synth;
  (* src = "maquina.v:33" *)
  wire error_out_synth_temp;
  (* src = "maquina.v:20" *)
  output [4:0] errors_out_synth;
  (* onehot = 32'd1 *)
  wire [4:0] estado;
  (* src = "maquina.v:22" *)
  output idle_out_synth;
  (* src = "maquina.v:36" *)
  wire idle_out_synth_temp;
  (* src = "maquina.v:4" *)
  input init;
  (* src = "maquina.v:3" *)
  input reset;
  NAND _105_ (
    .A(FIFO_empties[1]),
    .B(FIFO_empties[0]),
    .Y(_084_)
  );
  NOT _106_ (
    .A(FIFO_empties[2]),
    .Y(_085_)
  );
  NOT _107_ (
    .A(FIFO_empties[3]),
    .Y(_086_)
  );
  NOR _108_ (
    .A(_086_),
    .B(_085_),
    .Y(_087_)
  );
  NAND _109_ (
    .A(_087_),
    .B(FIFO_empties[4]),
    .Y(_088_)
  );
  NOR _110_ (
    .A(_088_),
    .B(_084_),
    .Y(_089_)
  );
  NOT _111_ (
    .A(FIFO_errors[0]),
    .Y(_090_)
  );
  NOT _112_ (
    .A(FIFO_errors[1]),
    .Y(_091_)
  );
  NAND _113_ (
    .A(_091_),
    .B(_090_),
    .Y(_092_)
  );
  NOT _114_ (
    .A(FIFO_errors[4]),
    .Y(_093_)
  );
  NOR _115_ (
    .A(FIFO_errors[3]),
    .B(FIFO_errors[2]),
    .Y(_094_)
  );
  NAND _116_ (
    .A(_094_),
    .B(_093_),
    .Y(_095_)
  );
  NOR _117_ (
    .A(_095_),
    .B(_092_),
    .Y(_096_)
  );
  NOT _118_ (
    .A(reset),
    .Y(_097_)
  );
  NOR _119_ (
    .A(_097_),
    .B(init),
    .Y(_098_)
  );
  NOR _120_ (
    .A(estado[2]),
    .B(estado[3]),
    .Y(_099_)
  );
  NOT _121_ (
    .A(_099_),
    .Y(_100_)
  );
  NAND _122_ (
    .A(_100_),
    .B(_098_),
    .Y(_101_)
  );
  NOT _123_ (
    .A(_101_),
    .Y(_102_)
  );
  NAND _124_ (
    .A(_102_),
    .B(_096_),
    .Y(_103_)
  );
  NOR _125_ (
    .A(_103_),
    .B(_089_),
    .Y(_080_)
  );
  NOT _126_ (
    .A(estado[1]),
    .Y(_104_)
  );
  NAND _127_ (
    .A(reset),
    .B(_104_),
    .Y(_081_)
  );
  NOT _128_ (
    .A(init),
    .Y(_011_)
  );
  NOR _129_ (
    .A(_100_),
    .B(estado[4]),
    .Y(_012_)
  );
  NOR _130_ (
    .A(_012_),
    .B(_011_),
    .Y(_013_)
  );
  NOR _131_ (
    .A(_013_),
    .B(estado[0]),
    .Y(_014_)
  );
  NOR _132_ (
    .A(_014_),
    .B(_097_),
    .Y(_082_)
  );
  NAND _133_ (
    .A(_098_),
    .B(estado[4]),
    .Y(_015_)
  );
  NOR _134_ (
    .A(FIFO_errors[4]),
    .B(FIFO_errors[2]),
    .Y(_016_)
  );
  NOR _135_ (
    .A(_092_),
    .B(FIFO_errors[3]),
    .Y(_017_)
  );
  NAND _136_ (
    .A(_017_),
    .B(_016_),
    .Y(_018_)
  );
  NOR _137_ (
    .A(_101_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _138_ (
    .A(_019_),
    .B(_089_),
    .Y(_020_)
  );
  NAND _139_ (
    .A(_020_),
    .B(_015_),
    .Y(_083_)
  );
  NOR _140_ (
    .A(_097_),
    .B(_090_),
    .Y(_000_[0])
  );
  NOR _141_ (
    .A(_097_),
    .B(_091_),
    .Y(_000_[1])
  );
  NOT _142_ (
    .A(FIFO_errors[2]),
    .Y(_021_)
  );
  NOR _143_ (
    .A(_097_),
    .B(_021_),
    .Y(_000_[2])
  );
  NOT _144_ (
    .A(FIFO_errors[3]),
    .Y(_022_)
  );
  NOR _145_ (
    .A(_097_),
    .B(_022_),
    .Y(_000_[3])
  );
  NOR _146_ (
    .A(_097_),
    .B(_093_),
    .Y(_000_[4])
  );
  NOT _147_ (
    .A(estado[3]),
    .Y(_023_)
  );
  NOR _148_ (
    .A(_097_),
    .B(_023_),
    .Y(_010_)
  );
  NOT _149_ (
    .A(estado[2]),
    .Y(_024_)
  );
  NOR _150_ (
    .A(_097_),
    .B(_024_),
    .Y(_007_)
  );
  NOT _151_ (
    .A(FIFO_errors_temp[0]),
    .Y(_025_)
  );
  NAND _152_ (
    .A(reset),
    .B(estado[1]),
    .Y(_026_)
  );
  NOR _153_ (
    .A(_026_),
    .B(_025_),
    .Y(_009_[0])
  );
  NOT _154_ (
    .A(FIFO_errors_temp[1]),
    .Y(_027_)
  );
  NOR _155_ (
    .A(_026_),
    .B(_027_),
    .Y(_009_[1])
  );
  NOT _156_ (
    .A(FIFO_errors_temp[2]),
    .Y(_028_)
  );
  NOR _157_ (
    .A(_026_),
    .B(_028_),
    .Y(_009_[2])
  );
  NOT _158_ (
    .A(FIFO_errors_temp[3]),
    .Y(_029_)
  );
  NOR _159_ (
    .A(_026_),
    .B(_029_),
    .Y(_009_[3])
  );
  NOT _160_ (
    .A(FIFO_errors_temp[4]),
    .Y(_030_)
  );
  NOR _161_ (
    .A(_026_),
    .B(_030_),
    .Y(_009_[4])
  );
  NOT _162_ (
    .A(_026_),
    .Y(_008_)
  );
  NOR _163_ (
    .A(Umbral_D_bajo_interno_synth[0]),
    .B(estado[4]),
    .Y(_031_)
  );
  NOT _164_ (
    .A(Umbral_D_bajo[0]),
    .Y(_033_)
  );
  NAND _165_ (
    .A(_033_),
    .B(estado[4]),
    .Y(_034_)
  );
  NAND _166_ (
    .A(_034_),
    .B(reset),
    .Y(_035_)
  );
  NOR _167_ (
    .A(_035_),
    .B(_031_),
    .Y(_002_[0])
  );
  NOR _168_ (
    .A(Umbral_D_bajo_interno_synth[1]),
    .B(estado[4]),
    .Y(_036_)
  );
  NOT _169_ (
    .A(Umbral_D_bajo[1]),
    .Y(_037_)
  );
  NAND _170_ (
    .A(_037_),
    .B(estado[4]),
    .Y(_038_)
  );
  NAND _171_ (
    .A(_038_),
    .B(reset),
    .Y(_039_)
  );
  NOR _172_ (
    .A(_039_),
    .B(_036_),
    .Y(_002_[1])
  );
  NOR _173_ (
    .A(Umbral_D_alto_interno_synth[0]),
    .B(estado[4]),
    .Y(_040_)
  );
  NOT _174_ (
    .A(Umbral_D_alto[0]),
    .Y(_041_)
  );
  NAND _175_ (
    .A(_041_),
    .B(estado[4]),
    .Y(_042_)
  );
  NAND _176_ (
    .A(_042_),
    .B(reset),
    .Y(_043_)
  );
  NOR _177_ (
    .A(_043_),
    .B(_040_),
    .Y(_001_[0])
  );
  NOR _178_ (
    .A(Umbral_D_alto_interno_synth[1]),
    .B(estado[4]),
    .Y(_044_)
  );
  NOT _179_ (
    .A(Umbral_D_alto[1]),
    .Y(_045_)
  );
  NAND _180_ (
    .A(_045_),
    .B(estado[4]),
    .Y(_046_)
  );
  NAND _181_ (
    .A(_046_),
    .B(reset),
    .Y(_047_)
  );
  NOR _182_ (
    .A(_047_),
    .B(_044_),
    .Y(_001_[1])
  );
  NOR _183_ (
    .A(Umbral_VC_bajo_interno_synth[0]),
    .B(estado[4]),
    .Y(_048_)
  );
  NOT _184_ (
    .A(Umbral_VC_bajo[0]),
    .Y(_049_)
  );
  NAND _185_ (
    .A(_049_),
    .B(estado[4]),
    .Y(_050_)
  );
  NAND _186_ (
    .A(_050_),
    .B(reset),
    .Y(_051_)
  );
  NOR _187_ (
    .A(_051_),
    .B(_048_),
    .Y(_006_[0])
  );
  NOR _188_ (
    .A(Umbral_VC_bajo_interno_synth[1]),
    .B(estado[4]),
    .Y(_052_)
  );
  NOT _189_ (
    .A(Umbral_VC_bajo[1]),
    .Y(_053_)
  );
  NAND _190_ (
    .A(_053_),
    .B(estado[4]),
    .Y(_054_)
  );
  NAND _191_ (
    .A(_054_),
    .B(reset),
    .Y(_055_)
  );
  NOR _192_ (
    .A(_055_),
    .B(_052_),
    .Y(_006_[1])
  );
  NOR _193_ (
    .A(Umbral_VC_alto_interno_synth[0]),
    .B(estado[4]),
    .Y(_056_)
  );
  NOT _194_ (
    .A(Umbral_VC_alto[0]),
    .Y(_057_)
  );
  NAND _195_ (
    .A(_057_),
    .B(estado[4]),
    .Y(_058_)
  );
  NAND _196_ (
    .A(_058_),
    .B(reset),
    .Y(_059_)
  );
  NOR _197_ (
    .A(_059_),
    .B(_056_),
    .Y(_005_[0])
  );
  NOR _198_ (
    .A(Umbral_VC_alto_interno_synth[1]),
    .B(estado[4]),
    .Y(_060_)
  );
  NOT _199_ (
    .A(Umbral_VC_alto[1]),
    .Y(_061_)
  );
  NAND _200_ (
    .A(_061_),
    .B(estado[4]),
    .Y(_062_)
  );
  NAND _201_ (
    .A(_062_),
    .B(reset),
    .Y(_063_)
  );
  NOR _202_ (
    .A(_063_),
    .B(_060_),
    .Y(_005_[1])
  );
  NOR _203_ (
    .A(Umbral_MF_bajo_interno_synth[0]),
    .B(estado[4]),
    .Y(_064_)
  );
  NOT _204_ (
    .A(Umbral_MF_bajo[0]),
    .Y(_065_)
  );
  NAND _205_ (
    .A(_065_),
    .B(estado[4]),
    .Y(_066_)
  );
  NAND _206_ (
    .A(_066_),
    .B(reset),
    .Y(_067_)
  );
  NOR _207_ (
    .A(_067_),
    .B(_064_),
    .Y(_004_[0])
  );
  NOR _208_ (
    .A(Umbral_MF_bajo_interno_synth[1]),
    .B(estado[4]),
    .Y(_068_)
  );
  NOT _209_ (
    .A(Umbral_MF_bajo[1]),
    .Y(_069_)
  );
  NAND _210_ (
    .A(_069_),
    .B(estado[4]),
    .Y(_070_)
  );
  NAND _211_ (
    .A(_070_),
    .B(reset),
    .Y(_071_)
  );
  NOR _212_ (
    .A(_071_),
    .B(_068_),
    .Y(_004_[1])
  );
  NOR _213_ (
    .A(Umbral_MF_alto_interno_synth[0]),
    .B(estado[4]),
    .Y(_072_)
  );
  NOT _214_ (
    .A(Umbral_MF_alto[0]),
    .Y(_073_)
  );
  NAND _215_ (
    .A(_073_),
    .B(estado[4]),
    .Y(_074_)
  );
  NAND _216_ (
    .A(_074_),
    .B(reset),
    .Y(_075_)
  );
  NOR _217_ (
    .A(_075_),
    .B(_072_),
    .Y(_003_[0])
  );
  NOR _218_ (
    .A(Umbral_MF_alto_interno_synth[1]),
    .B(estado[4]),
    .Y(_076_)
  );
  NOT _219_ (
    .A(Umbral_MF_alto[1]),
    .Y(_077_)
  );
  NAND _220_ (
    .A(_077_),
    .B(estado[4]),
    .Y(_078_)
  );
  NAND _221_ (
    .A(_078_),
    .B(reset),
    .Y(_079_)
  );
  NOR _222_ (
    .A(_079_),
    .B(_076_),
    .Y(_003_[1])
  );
  NOR _223_ (
    .A(_101_),
    .B(_096_),
    .Y(_032_)
  );
  DFF _224_ (
    .C(clk),
    .D(_081_),
    .Q(estado[0])
  );
  DFF _225_ (
    .C(clk),
    .D(_032_),
    .Q(estado[1])
  );
  DFF _226_ (
    .C(clk),
    .D(_080_),
    .Q(estado[2])
  );
  DFF _227_ (
    .C(clk),
    .D(_083_),
    .Q(estado[3])
  );
  DFF _228_ (
    .C(clk),
    .D(_082_),
    .Q(estado[4])
  );
  DFF _229_ (
    .C(clk),
    .D(_003_[0]),
    .Q(Umbral_MF_alto_interno_synth[0])
  );
  DFF _230_ (
    .C(clk),
    .D(_003_[1]),
    .Q(Umbral_MF_alto_interno_synth[1])
  );
  DFF _231_ (
    .C(clk),
    .D(_004_[0]),
    .Q(Umbral_MF_bajo_interno_synth[0])
  );
  DFF _232_ (
    .C(clk),
    .D(_004_[1]),
    .Q(Umbral_MF_bajo_interno_synth[1])
  );
  DFF _233_ (
    .C(clk),
    .D(_005_[0]),
    .Q(Umbral_VC_alto_interno_synth[0])
  );
  DFF _234_ (
    .C(clk),
    .D(_005_[1]),
    .Q(Umbral_VC_alto_interno_synth[1])
  );
  DFF _235_ (
    .C(clk),
    .D(_006_[0]),
    .Q(Umbral_VC_bajo_interno_synth[0])
  );
  DFF _236_ (
    .C(clk),
    .D(_006_[1]),
    .Q(Umbral_VC_bajo_interno_synth[1])
  );
  DFF _237_ (
    .C(clk),
    .D(_001_[0]),
    .Q(Umbral_D_alto_interno_synth[0])
  );
  DFF _238_ (
    .C(clk),
    .D(_001_[1]),
    .Q(Umbral_D_alto_interno_synth[1])
  );
  DFF _239_ (
    .C(clk),
    .D(_002_[0]),
    .Q(Umbral_D_bajo_interno_synth[0])
  );
  DFF _240_ (
    .C(clk),
    .D(_002_[1]),
    .Q(Umbral_D_bajo_interno_synth[1])
  );
  DFF _241_ (
    .C(clk),
    .D(_008_),
    .Q(error_out_synth)
  );
  DFF _242_ (
    .C(clk),
    .D(_009_[0]),
    .Q(errors_out_synth[0])
  );
  DFF _243_ (
    .C(clk),
    .D(_009_[1]),
    .Q(errors_out_synth[1])
  );
  DFF _244_ (
    .C(clk),
    .D(_009_[2]),
    .Q(errors_out_synth[2])
  );
  DFF _245_ (
    .C(clk),
    .D(_009_[3]),
    .Q(errors_out_synth[3])
  );
  DFF _246_ (
    .C(clk),
    .D(_009_[4]),
    .Q(errors_out_synth[4])
  );
  DFF _247_ (
    .C(clk),
    .D(_007_),
    .Q(active_out_synth)
  );
  DFF _248_ (
    .C(clk),
    .D(_010_),
    .Q(idle_out_synth)
  );
  DFF _249_ (
    .C(clk),
    .D(_000_[0]),
    .Q(FIFO_errors_temp[0])
  );
  DFF _250_ (
    .C(clk),
    .D(_000_[1]),
    .Q(FIFO_errors_temp[1])
  );
  DFF _251_ (
    .C(clk),
    .D(_000_[2]),
    .Q(FIFO_errors_temp[2])
  );
  DFF _252_ (
    .C(clk),
    .D(_000_[3]),
    .Q(FIFO_errors_temp[3])
  );
  DFF _253_ (
    .C(clk),
    .D(_000_[4]),
    .Q(FIFO_errors_temp[4])
  );
  assign active_out_synth_temp = estado[2];
  assign error_out_synth_temp = estado[1];
  assign idle_out_synth_temp = estado[3];
endmodule
