/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "demux.v:1" *)
module demux_Sint(data_in, valid_in, selector, data_out_0, data_out_1, push_0, push_1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "demux.v:2" *)
  input [5:0] data_in;
  (* src = "demux.v:5" *)
  output [5:0] data_out_0;
  (* src = "demux.v:6" *)
  output [5:0] data_out_1;
  (* src = "demux.v:7" *)
  output push_0;
  (* src = "demux.v:8" *)
  output push_1;
  (* src = "demux.v:4" *)
  input selector;
  (* src = "demux.v:3" *)
  input valid_in;
  NOT _09_ (
    .A(selector),
    .Y(_00_)
  );
  NOT _10_ (
    .A(data_in[0]),
    .Y(_01_)
  );
  NOT _11_ (
    .A(data_in[1]),
    .Y(_02_)
  );
  NOT _12_ (
    .A(data_in[2]),
    .Y(_03_)
  );
  NOT _13_ (
    .A(data_in[3]),
    .Y(_04_)
  );
  NOT _14_ (
    .A(data_in[4]),
    .Y(_05_)
  );
  NOT _15_ (
    .A(data_in[5]),
    .Y(_06_)
  );
  NAND _16_ (
    .A(selector),
    .B(valid_in),
    .Y(_07_)
  );
  NOT _17_ (
    .A(_07_),
    .Y(push_1)
  );
  NOR _18_ (
    .A(_01_),
    .B(_07_),
    .Y(data_out_1[0])
  );
  NOR _19_ (
    .A(_02_),
    .B(_07_),
    .Y(data_out_1[1])
  );
  NOR _20_ (
    .A(_03_),
    .B(_07_),
    .Y(data_out_1[2])
  );
  NOR _21_ (
    .A(_04_),
    .B(_07_),
    .Y(data_out_1[3])
  );
  NOR _22_ (
    .A(_05_),
    .B(_07_),
    .Y(data_out_1[4])
  );
  NOR _23_ (
    .A(_06_),
    .B(_07_),
    .Y(data_out_1[5])
  );
  NAND _24_ (
    .A(_00_),
    .B(valid_in),
    .Y(_08_)
  );
  NOT _25_ (
    .A(_08_),
    .Y(push_0)
  );
  NOR _26_ (
    .A(_01_),
    .B(_08_),
    .Y(data_out_0[0])
  );
  NOR _27_ (
    .A(_02_),
    .B(_08_),
    .Y(data_out_0[1])
  );
  NOR _28_ (
    .A(_03_),
    .B(_08_),
    .Y(data_out_0[2])
  );
  NOR _29_ (
    .A(_04_),
    .B(_08_),
    .Y(data_out_0[3])
  );
  NOR _30_ (
    .A(_05_),
    .B(_08_),
    .Y(data_out_0[4])
  );
  NOR _31_ (
    .A(_06_),
    .B(_08_),
    .Y(data_out_0[5])
  );
endmodule
