/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "Empty_and_pause.v:1" *)
module Empty_and_pause_Sint(clk, reset_L, vc0_empty, vc1_empty, pause_d0, pause_d1, valid_vc0, valid_vc1, pop_vc0, pop_vc1);
  (* src = "Empty_and_pause.v:26" *)
  wire _00_;
  (* src = "Empty_and_pause.v:26" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  (* src = "Empty_and_pause.v:2" *)
  input clk;
  (* src = "Empty_and_pause.v:6" *)
  input pause_d0;
  (* src = "Empty_and_pause.v:7" *)
  input pause_d1;
  (* src = "Empty_and_pause.v:10" *)
  output pop_vc0;
  (* src = "Empty_and_pause.v:11" *)
  output pop_vc1;
  (* src = "Empty_and_pause.v:3" *)
  input reset_L;
  (* src = "Empty_and_pause.v:8" *)
  output valid_vc0;
  (* src = "Empty_and_pause.v:9" *)
  output valid_vc1;
  (* src = "Empty_and_pause.v:4" *)
  input vc0_empty;
  (* src = "Empty_and_pause.v:5" *)
  input vc1_empty;
  NOT _06_ (
    .A(reset_L),
    .Y(_02_)
  );
  NOT _07_ (
    .A(vc1_empty),
    .Y(pop_vc1)
  );
  NOT _08_ (
    .A(pause_d1),
    .Y(_03_)
  );
  NOR _09_ (
    .A(_02_),
    .B(vc1_empty),
    .Y(_01_)
  );
  NOR _10_ (
    .A(vc0_empty),
    .B(pause_d0),
    .Y(_04_)
  );
  NAND _11_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  NOT _12_ (
    .A(_05_),
    .Y(pop_vc0)
  );
  NOR _13_ (
    .A(_02_),
    .B(_05_),
    .Y(_00_)
  );
  (* src = "Empty_and_pause.v:26" *)
  DFF _14_ (
    .C(clk),
    .D(_00_),
    .Q(valid_vc0)
  );
  (* src = "Empty_and_pause.v:26" *)
  DFF _15_ (
    .C(clk),
    .D(_01_),
    .Q(valid_vc1)
  );
endmodule
