/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "mux.v:1" *)
module mux_Sint (data_in_0, valid_in0, data_in_1, valid_in1, data_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "mux.v:2" *)
  input [5:0] data_in_0;
  (* src = "mux.v:4" *)
  input [5:0] data_in_1;
  (* src = "mux.v:6" *)
  output [5:0] data_out;
  (* src = "mux.v:3" *)
  input valid_in0;
  (* src = "mux.v:5" *)
  input valid_in1;
  NAND _24_ (
    .A(data_in_1[0]),
    .B(valid_in1),
    .Y(_00_)
  );
  NAND _25_ (
    .A(data_in_0[0]),
    .B(valid_in0),
    .Y(_01_)
  );
  NOR _26_ (
    .A(valid_in0),
    .B(_00_),
    .Y(_02_)
  );
  NOT _27_ (
    .A(_02_),
    .Y(_03_)
  );
  NAND _28_ (
    .A(_01_),
    .B(_03_),
    .Y(data_out[0])
  );
  NAND _29_ (
    .A(valid_in1),
    .B(data_in_1[1]),
    .Y(_04_)
  );
  NAND _30_ (
    .A(valid_in0),
    .B(data_in_0[1]),
    .Y(_05_)
  );
  NOR _31_ (
    .A(valid_in0),
    .B(_04_),
    .Y(_06_)
  );
  NOT _32_ (
    .A(_06_),
    .Y(_07_)
  );
  NAND _33_ (
    .A(_05_),
    .B(_07_),
    .Y(data_out[1])
  );
  NAND _34_ (
    .A(valid_in1),
    .B(data_in_1[2]),
    .Y(_08_)
  );
  NAND _35_ (
    .A(valid_in0),
    .B(data_in_0[2]),
    .Y(_09_)
  );
  NOR _36_ (
    .A(valid_in0),
    .B(_08_),
    .Y(_10_)
  );
  NOT _37_ (
    .A(_10_),
    .Y(_11_)
  );
  NAND _38_ (
    .A(_09_),
    .B(_11_),
    .Y(data_out[2])
  );
  NAND _39_ (
    .A(valid_in1),
    .B(data_in_1[3]),
    .Y(_12_)
  );
  NAND _40_ (
    .A(valid_in0),
    .B(data_in_0[3]),
    .Y(_13_)
  );
  NOR _41_ (
    .A(valid_in0),
    .B(_12_),
    .Y(_14_)
  );
  NOT _42_ (
    .A(_14_),
    .Y(_15_)
  );
  NAND _43_ (
    .A(_13_),
    .B(_15_),
    .Y(data_out[3])
  );
  NAND _44_ (
    .A(valid_in1),
    .B(data_in_1[4]),
    .Y(_16_)
  );
  NAND _45_ (
    .A(valid_in0),
    .B(data_in_0[4]),
    .Y(_17_)
  );
  NOR _46_ (
    .A(valid_in0),
    .B(_16_),
    .Y(_18_)
  );
  NOT _47_ (
    .A(_18_),
    .Y(_19_)
  );
  NAND _48_ (
    .A(_17_),
    .B(_19_),
    .Y(data_out[4])
  );
  NAND _49_ (
    .A(valid_in1),
    .B(data_in_1[5]),
    .Y(_20_)
  );
  NAND _50_ (
    .A(valid_in0),
    .B(data_in_0[5]),
    .Y(_21_)
  );
  NOR _51_ (
    .A(valid_in0),
    .B(_20_),
    .Y(_22_)
  );
  NOT _52_ (
    .A(_22_),
    .Y(_23_)
  );
  NAND _53_ (
    .A(_21_),
    .B(_23_),
    .Y(data_out[5])
  );
endmodule
