/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "Pop_Main_and_Valid.v:1" *)
module Pop_Main_and_Valid_Sint(clk, reset_L, empy_main_FIFO, pause_vc0, pause_vc1, pop_Main, valid_pop_out);
  (* src = "Pop_Main_and_Valid.v:17" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "Pop_Main_and_Valid.v:2" *)
  input clk;
  (* src = "Pop_Main_and_Valid.v:4" *)
  input empy_main_FIFO;
  (* src = "Pop_Main_and_Valid.v:5" *)
  input pause_vc0;
  (* src = "Pop_Main_and_Valid.v:6" *)
  input pause_vc1;
  (* src = "Pop_Main_and_Valid.v:7" *)
  output pop_Main;
  (* src = "Pop_Main_and_Valid.v:3" *)
  input reset_L;
  (* src = "Pop_Main_and_Valid.v:8" *)
  output valid_pop_out;
  NOT _05_ (
    .A(pause_vc1),
    .Y(_02_)
  );
  NOT _06_ (
    .A(reset_L),
    .Y(_03_)
  );
  NOR _07_ (
    .A(empy_main_FIFO),
    .B(pause_vc0),
    .Y(_04_)
  );
  NAND _08_ (
    .A(_02_),
    .B(_04_),
    .Y(_01_)
  );
  NOT _09_ (
    .A(_01_),
    .Y(pop_Main)
  );
  NOR _10_ (
    .A(_03_),
    .B(_01_),
    .Y(_00_)
  );
  (* src = "Pop_Main_and_Valid.v:17" *)
  DFF _11_ (
    .C(clk),
    .D(_00_),
    .Q(valid_pop_out)
  );
endmodule
